//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adm_ApiProvider
    {
        public int IdApiProvider { get; set; }
        public int IdProveedor { get; set; }
        public string UrlBase { get; set; }
        public string Metodo { get; set; }
        public bool Activo { get; set; }
        public Nullable<bool> Borrado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaEliminacion { get; set; }
        public string Token { get; set; }
        public string Dominio { get; set; }
    
        public virtual Adm_Proveedor Adm_Proveedor { get; set; }
    }
}
