//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adm_HistoricoLoginAdmSuscripcion
    {
        public int IdHistoricoLoginAdmSuscripcion { get; set; }
        public string Email { get; set; }
        public int CodigoOtp { get; set; }
        public int IdCatEvento { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Info { get; set; }
        public string Ip { get; set; }
        public bool Activo { get; set; }
        public string IdEnvioApiAlphaOtp { get; set; }
        public Nullable<System.DateTime> FechaMailEnvioOtp { get; set; }
    
        public virtual CatEvento CatEvento { get; set; }
    }
}
