//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adm_HistoryLoginDataManager
    {
        public int IdHistoryLoginDataManager { get; set; }
        public string Usuario { get; set; }
        public int IdCatEvento { get; set; }
        public System.DateTime FechaAcceso { get; set; }
        public string Info { get; set; }
        public string Ip { get; set; }
    
        public virtual CatEvento CatEvento { get; set; }
    }
}
