//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEMPL_DATOSPOSTULANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BEMPL_DATOSPOSTULANTE()
        {
            this.BEMPL_EXPERIENCIA_LABORAL = new HashSet<BEMPL_EXPERIENCIA_LABORAL>();
            this.BEMPL_IDIOMAS_POSTULANTE = new HashSet<BEMPL_IDIOMAS_POSTULANTE>();
            this.BEMPL_REFERENCIAS_LABORA = new HashSet<BEMPL_REFERENCIAS_LABORA>();
        }
    
        public int IdPostulante { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<int> IdTipoIdentificacion { get; set; }
        public string Identificacion { get; set; }
        public Nullable<int> IdGenero { get; set; }
        public Nullable<int> IdEstadoCivil { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public Nullable<bool> MoilizacionPropia { get; set; }
        public Nullable<bool> CarnetDiscapacidad { get; set; }
        public Nullable<int> DiasCambio { get; set; }
        public string AreaInteresCapacitacion { get; set; }
        public string UrlAdjuntoCV { get; set; }
        public string UrlVideo { get; set; }
        public Nullable<decimal> AspiracionSalarial { get; set; }
        public string UrlDiscapacidad { get; set; }
        public string DetalleDiscapacidades { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Celular { get; set; }
        public Nullable<int> PorcentajeHojaVida { get; set; }
        public string UrlImagenPerfil { get; set; }
        public Nullable<int> IdNacionalidad { get; set; }
        public Nullable<bool> IsEnviadoEmailCandidato { get; set; }
        public Nullable<System.DateTime> FechaHoraEnviadoEmailCandidato { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string ModificadoPor { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<int> AniosExperiencia { get; set; }
        public Nullable<int> IdCapacitacion { get; set; }
        public string Otros { get; set; }
    
        public virtual BEMPL_CAT_CIUDAD BEMPL_CAT_CIUDAD { get; set; }
        public virtual BEMPL_CAT_ESTADO_CIVIL BEMPL_CAT_ESTADO_CIVIL { get; set; }
        public virtual BEMPL_CAT_GENERO BEMPL_CAT_GENERO { get; set; }
        public virtual BEMPL_CAT_NACIONALIDAD BEMPL_CAT_NACIONALIDAD { get; set; }
        public virtual BEMPL_CAT_PROVINCIAS BEMPL_CAT_PROVINCIAS { get; set; }
        public virtual BEMPL_CAT_TIPO_IDENTIFICACION BEMPL_CAT_TIPO_IDENTIFICACION { get; set; }
        public virtual BEMPL_USUARIO BEMPL_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BEMPL_EXPERIENCIA_LABORAL> BEMPL_EXPERIENCIA_LABORAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BEMPL_IDIOMAS_POSTULANTE> BEMPL_IDIOMAS_POSTULANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BEMPL_REFERENCIAS_LABORA> BEMPL_REFERENCIAS_LABORA { get; set; }
        public virtual BEMPL_CAT_CAPACITACIONES BEMPL_CAT_CAPACITACIONES { get; set; }
    }
}
