//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EV_Direccion
    {
        public int IdDireccion { get; set; }
        public string Direccion { get; set; }
        public int IdUrlDireccion { get; set; }
    
        public virtual EV_UrlDireccion EV_UrlDireccion { get; set; }
    }
}
