//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Event1 = new HashSet<Event>();
            this.ResourceResources_EventEvents = new HashSet<ResourceResources_EventEvents>();
        }
    
        public System.Guid Oid { get; set; }
        public string ResourceIds { get; set; }
        public Nullable<System.Guid> RecurrencePattern { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartOn { get; set; }
        public Nullable<System.DateTime> EndOn { get; set; }
        public Nullable<bool> AllDay { get; set; }
        public string Location { get; set; }
        public Nullable<int> Label { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<double> RemindIn { get; set; }
        public string ReminderInfoXml { get; set; }
        public Nullable<System.DateTime> AlarmTime { get; set; }
        public Nullable<bool> IsPostponed { get; set; }
        public string RecurrenceInfoXml { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Event1 { get; set; }
        public virtual Event Event2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceResources_EventEvents> ResourceResources_EventEvents { get; set; }
    }
}
