//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GC_Usuario
    {
        public int IdUsuario { get; set; }
        public int IdRol { get; set; }
        public Nullable<int> cod_afil { get; set; }
        public string Usuario { get; set; }
        public string Contrasenia { get; set; }
    }
}
