//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KpiInstance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KpiInstance()
        {
            this.KpiDefinition1 = new HashSet<KpiDefinition>();
            this.KpiHistoryItem = new HashSet<KpiHistoryItem>();
            this.KpiScorecardScorecards_KpiInstanceIndicators = new HashSet<KpiScorecardScorecards_KpiInstanceIndicators>();
        }
    
        public System.Guid Oid { get; set; }
        public Nullable<System.DateTime> ForceMeasurementDateTime { get; set; }
        public Nullable<System.Guid> KpiDefinition { get; set; }
        public string Settings { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KpiDefinition> KpiDefinition1 { get; set; }
        public virtual KpiDefinition KpiDefinition2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KpiHistoryItem> KpiHistoryItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KpiScorecardScorecards_KpiInstanceIndicators> KpiScorecardScorecards_KpiInstanceIndicators { get; set; }
    }
}
