//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KpiScorecardScorecards_KpiInstanceIndicators
    {
        public Nullable<System.Guid> Indicators { get; set; }
        public Nullable<System.Guid> Scorecards { get; set; }
        public System.Guid OID { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
    
        public virtual KpiInstance KpiInstance { get; set; }
        public virtual KpiScorecard KpiScorecard { get; set; }
    }
}
