//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mAF_MaestroActivos
    {
        public int IdActivo { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> CodigoActivo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdTipoActivo { get; set; }
        public Nullable<int> IdClase { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
        public Nullable<int> VidaUtil { get; set; }
        public Nullable<int> PeriodosDepreciados { get; set; }
        public Nullable<decimal> ValorOriginal { get; set; }
        public Nullable<decimal> DepreciacionAcumulada { get; set; }
        public Nullable<System.DateTime> FechaUltimaDepreciacion { get; set; }
        public Nullable<decimal> ValorAlicuota { get; set; }
        public Nullable<decimal> ValorRescate { get; set; }
        public Nullable<System.DateTime> FechaIncorporacion { get; set; }
        public Nullable<int> IdActivoAsociado { get; set; }
        public Nullable<int> IdColor { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public string Serial { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string NombreProveedor { get; set; }
        public string FacturaCompra { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public string NombreProveedorGarantia { get; set; }
        public Nullable<System.DateTime> FechaVencimientoGarantia { get; set; }
        public Nullable<System.DateTime> FechaDesincorporacion { get; set; }
        public string EmpresaAseguradora { get; set; }
        public string NumeroPoliza { get; set; }
        public Nullable<System.DateTime> FechaVencimientoPoliza { get; set; }
        public Nullable<decimal> ValorPrimaSeguro { get; set; }
        public Nullable<decimal> ValorAsegurado { get; set; }
        public Nullable<int> IdSituacion { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdMotivoBaja { get; set; }
        public Nullable<int> IdCentroCostos { get; set; }
        public Nullable<int> Operacion { get; set; }
    
        public virtual tAF_MaestroActivos tAF_MaestroActivos { get; set; }
        public virtual tGN_CentrosCostos tGN_CentrosCostos { get; set; }
        public virtual tAF_Clases tAF_Clases { get; set; }
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        public virtual tAF_Estados tAF_Estados { get; set; }
        public virtual tAF_MotivosBaja tAF_MotivosBaja { get; set; }
        public virtual tAF_Situaciones tAF_Situaciones { get; set; }
        public virtual tAF_TiposActivos tAF_TiposActivos { get; set; }
        public virtual tAF_Ubicaciones tAF_Ubicaciones { get; set; }
    }
}
