//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredInstances
    {
        public int InstancesId { get; set; }
        public string InstanceName { get; set; }
        public string ServerName { get; set; }
        public System.DateTime DateAddedUtc { get; set; }
    }
}
