//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDataV2
    {
        public int Id { get; set; }
        public bool IsInplaceReport { get; set; }
        public string DisplayName { get; set; }
        public string DataTypeName { get; set; }
        public string PredefinedReportTypeName { get; set; }
        public byte[] Content { get; set; }
        public string ParametersObjectTypeName { get; set; }
        public System.Guid Oid { get; set; }
        public string ObjectTypeName { get; set; }
        public string Name { get; set; }
        public string PredefinedReportType { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    }
}
