//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_Pulsador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sec_Pulsador()
        {
            this.Sec_Alerta = new HashSet<Sec_Alerta>();
        }
    
        public string IdPulsador { get; set; }
        public string NumeroSerie { get; set; }
        public int IdCatTipoPulsador { get; set; }
        public int IdProveedor { get; set; }
        public int IdMarca { get; set; }
        public string Modelo { get; set; }
        public int IdCatEstadoEquipo { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<System.DateTime> FechaEliminacion { get; set; }
    
        public virtual CatEstadoEquipo CatEstadoEquipo { get; set; }
        public virtual CatTipoPulsador CatTipoPulsador { get; set; }
        public virtual Adm_Marca Adm_Marca { get; set; }
        public virtual Adm_Proveedor Adm_Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sec_Alerta> Sec_Alerta { get; set; }
    }
}
