//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecuritySystemRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecuritySystemRole()
        {
            this.SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoles = new HashSet<SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoles>();
            this.SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoles1 = new HashSet<SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoles>();
            this.SecuritySystemRoleRoles_DashboardDefinitionDashboardDefinitions = new HashSet<SecuritySystemRoleRoles_DashboardDefinitionDashboardDefinitions>();
            this.SecuritySystemTypePermissionsObject = new HashSet<SecuritySystemTypePermissionsObject>();
            this.SecuritySystemUserUsers_SecuritySystemRoleRoles = new HashSet<SecuritySystemUserUsers_SecuritySystemRoleRoles>();
        }
    
        public System.Guid Oid { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsAdministrative { get; set; }
        public Nullable<bool> CanEditModel { get; set; }
    
        public virtual XPObjectType XPObjectType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoles> SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoles> SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecuritySystemRoleRoles_DashboardDefinitionDashboardDefinitions> SecuritySystemRoleRoles_DashboardDefinitionDashboardDefinitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecuritySystemTypePermissionsObject> SecuritySystemTypePermissionsObject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecuritySystemUserUsers_SecuritySystemRoleRoles> SecuritySystemUserUsers_SecuritySystemRoleRoles { get; set; }
    }
}
