//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecuritySystemTypePermissionsObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecuritySystemTypePermissionsObject()
        {
            this.SecuritySystemMemberPermissionsObject = new HashSet<SecuritySystemMemberPermissionsObject>();
            this.SecuritySystemObjectPermissionsObject = new HashSet<SecuritySystemObjectPermissionsObject>();
        }
    
        public System.Guid Oid { get; set; }
        public string TargetType { get; set; }
        public Nullable<bool> AllowRead { get; set; }
        public Nullable<bool> AllowWrite { get; set; }
        public Nullable<bool> AllowCreate { get; set; }
        public Nullable<bool> AllowDelete { get; set; }
        public Nullable<bool> AllowNavigate { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<System.Guid> Owner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecuritySystemMemberPermissionsObject> SecuritySystemMemberPermissionsObject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecuritySystemObjectPermissionsObject> SecuritySystemObjectPermissionsObject { get; set; }
        public virtual SecuritySystemRole SecuritySystemRole { get; set; }
        public virtual XPObjectType XPObjectType { get; set; }
    }
}
