//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAF_Incorporaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tAF_Incorporaciones()
        {
            this.tAF_AnexosIncorporaciones = new HashSet<tAF_AnexosIncorporaciones>();
            this.tAF_AnexosIncorporaciones1 = new HashSet<tAF_AnexosIncorporaciones>();
        }
    
        public int IdIncorporacion { get; set; }
        public int IdEmpresa { get; set; }
        public int CodigoActivo { get; set; }
        public string CodigoBarras { get; set; }
        public decimal Cantidad { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdClase { get; set; }
        public int IdColor { get; set; }
        public int IdMaterialPrimario { get; set; }
        public Nullable<int> IdMaterialSecundario { get; set; }
        public Nullable<System.DateTime> FechaAdquisicion { get; set; }
        public System.DateTime FechaIncorporacion { get; set; }
        public decimal ValorOriginal { get; set; }
        public Nullable<decimal> ValorRescate { get; set; }
        public int IdTipoActivo { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public string Serial { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string FacturaCompra { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public int IdSituacion { get; set; }
        public int IdEstado { get; set; }
        public Nullable<int> IdMotivoBaja { get; set; }
        public Nullable<int> IdCentroCostos { get; set; }
        public int IdUbicacion { get; set; }
        public int IdEmpleado { get; set; }
        public string NombreProveedorGarantia { get; set; }
        public Nullable<int> MesesGarantia { get; set; }
        public Nullable<System.DateTime> FechaVencimientoGarantia { get; set; }
        public string EmpresaAseguradora { get; set; }
        public string NumeroPoliza { get; set; }
        public Nullable<System.DateTime> FechaVencimientoPoliza { get; set; }
        public Nullable<decimal> ValorPrimaSeguro { get; set; }
        public Nullable<decimal> ValorAsegurado { get; set; }
        public string Nota { get; set; }
        public Nullable<int> VidaUtil { get; set; }
        public Nullable<decimal> ValorAlicuota { get; set; }
        public Nullable<int> IdActivoAsociado { get; set; }
        public string NombreProveedor { get; set; }
        public Nullable<bool> Procesado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAF_AnexosIncorporaciones> tAF_AnexosIncorporaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAF_AnexosIncorporaciones> tAF_AnexosIncorporaciones1 { get; set; }
        public virtual tAF_Clases tAF_Clases { get; set; }
        public virtual tAF_Colores tAF_Colores { get; set; }
        public virtual tAF_Estados tAF_Estados { get; set; }
        public virtual tAF_MaestroActivos tAF_MaestroActivos { get; set; }
        public virtual tGN_CentrosCostos tGN_CentrosCostos { get; set; }
        public virtual tNM_Empleados tNM_Empleados { get; set; }
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        public virtual tCP_Proveedores tCP_Proveedores { get; set; }
        public virtual tAF_TiposActivos tAF_TiposActivos { get; set; }
        public virtual tAF_Ubicaciones tAF_Ubicaciones { get; set; }
        public virtual tAF_Marcas tAF_Marcas { get; set; }
        public virtual tAF_Materiales tAF_Materiales { get; set; }
        public virtual tAF_Materiales tAF_Materiales1 { get; set; }
        public virtual tAF_MotivosBaja tAF_MotivosBaja { get; set; }
        public virtual tAF_Situaciones tAF_Situaciones { get; set; }
    }
}
