//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCB_EstadoCuentaBancoGeneral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCB_EstadoCuentaBancoGeneral()
        {
            this.tCB_ConciliacionBancaria = new HashSet<tCB_ConciliacionBancaria>();
            this.tCB_MaestroConciliacionDet = new HashSet<tCB_MaestroConciliacionDet>();
        }
    
        public int IdEstadoCuentaBancoGeneral { get; set; }
        public Nullable<System.DateTime> FechaContable { get; set; }
        public string Referencia { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string NaturalezaDelMovimiento { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> SaldoContable { get; set; }
        public Nullable<int> IdEquivalenciaDeDocumento { get; set; }
        public Nullable<int> IdBancoCCQ { get; set; }
        public Nullable<bool> EstadoConciliado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCB_ConciliacionBancaria> tCB_ConciliacionBancaria { get; set; }
        public virtual tCB_EquivalenciaDeDocumento tCB_EquivalenciaDeDocumento { get; set; }
        public virtual tGN_BancosCCQ tGN_BancosCCQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCB_MaestroConciliacionDet> tCB_MaestroConciliacionDet { get; set; }
    }
}
