//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_AperturaCierreCaja
    {
        public int IdAperturaCierreCaja { get; set; }
        public int IdEmpresa { get; set; }
        public string IdSucursal { get; set; }
        public Nullable<int> NumeroCaja { get; set; }
        public int IdCajero { get; set; }
        public System.DateTime FechaHoraApertura { get; set; }
        public decimal ValorFijoInicialApertura { get; set; }
        public decimal ValorTCFijoApertura { get; set; }
        public decimal ValorChequesApertura { get; set; }
        public string EstadoCaja { get; set; }
        public decimal ValorEfectivoCierre { get; set; }
        public decimal ValorTCFijoCierre { get; set; }
        public decimal ValorChequesCierre { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public System.DateTime UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    }
}
