//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_CargosCabProyeccionCobro
    {
        public int IdCargoCab { get; set; }
        public decimal S1 { get; set; }
        public decimal S2 { get; set; }
        public decimal S3 { get; set; }
        public decimal S4 { get; set; }
        public decimal S5 { get; set; }
        public decimal S6 { get; set; }
        public decimal S7 { get; set; }
        public decimal S8 { get; set; }
        public decimal S9 { get; set; }
        public decimal S10 { get; set; }
        public decimal S11 { get; set; }
        public decimal S12 { get; set; }
        public decimal S13 { get; set; }
        public decimal S14 { get; set; }
        public decimal S15 { get; set; }
        public decimal S16 { get; set; }
        public decimal S17 { get; set; }
        public decimal S18 { get; set; }
        public decimal S19 { get; set; }
        public decimal S20 { get; set; }
        public decimal S21 { get; set; }
        public decimal S22 { get; set; }
        public decimal S23 { get; set; }
        public decimal S24 { get; set; }
        public decimal S25 { get; set; }
        public decimal S26 { get; set; }
        public decimal S27 { get; set; }
        public decimal S28 { get; set; }
        public decimal S29 { get; set; }
        public decimal S30 { get; set; }
    }
}
