//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_CargosCabProyeccionCobroPrevio
    {
        public int IdCargosCabProyeccionCobroPrevio { get; set; }
        public string NumeroDocumento { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
