//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_DescargosCabRelacionPagoTemp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCC_DescargosCabRelacionPagoTemp()
        {
            this.tCC_CajaIngresoChequeRelacionPagoTemp = new HashSet<tCC_CajaIngresoChequeRelacionPagoTemp>();
            this.tCC_CajaIngresoDepositoTransferenciaRelacionPagoTemp = new HashSet<tCC_CajaIngresoDepositoTransferenciaRelacionPagoTemp>();
            this.tCC_CajaIngresoEfectivoRelacionPagoTemp = new HashSet<tCC_CajaIngresoEfectivoRelacionPagoTemp>();
            this.tCC_CajaIngresoRetencionesRelacionPagoTemp = new HashSet<tCC_CajaIngresoRetencionesRelacionPagoTemp>();
            this.tCC_CajaIngresoTarjetaCreditoRelacionPagoTemp = new HashSet<tCC_CajaIngresoTarjetaCreditoRelacionPagoTemp>();
            this.tCC_CargosRelacionesPagoAuxiliar = new HashSet<tCC_CargosRelacionesPagoAuxiliar>();
            this.tGN_FormastGN_Formass_tCC_DescargosCabRelacionPagoTemptCC_DescargosCabsRelacionCobrosAux = new HashSet<tGN_FormastGN_Formass_tCC_DescargosCabRelacionPagoTemptCC_DescargosCabsRelacionCobrosAux>();
        }
    
        public int IdDescargoCab { get; set; }
        public Nullable<int> IdGrupoComprobante { get; set; }
        public int IdCliente { get; set; }
        public int IdTipoDocumento { get; set; }
        public int IdEmpresa { get; set; }
        public int IdPeriodoContable { get; set; }
        public Nullable<decimal> SubtotalIva { get; set; }
        public Nullable<decimal> Subtotal0 { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> TotalDescuento { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<int> IdEstadoDocumento { get; set; }
        public Nullable<long> IdRelacionPago { get; set; }
        public Nullable<long> IdRelacionPagoOriginal { get; set; }
        public Nullable<int> IdTipoCobro { get; set; }
        public Nullable<int> IdCaja { get; set; }
        public string NumeroDeposito { get; set; }
        public Nullable<bool> EsDepositoDefinitivo { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<int> IdCobrador { get; set; }
    
        public virtual tCC_Caja tCC_Caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CajaIngresoChequeRelacionPagoTemp> tCC_CajaIngresoChequeRelacionPagoTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CajaIngresoDepositoTransferenciaRelacionPagoTemp> tCC_CajaIngresoDepositoTransferenciaRelacionPagoTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CajaIngresoEfectivoRelacionPagoTemp> tCC_CajaIngresoEfectivoRelacionPagoTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CajaIngresoRetencionesRelacionPagoTemp> tCC_CajaIngresoRetencionesRelacionPagoTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CajaIngresoTarjetaCreditoRelacionPagoTemp> tCC_CajaIngresoTarjetaCreditoRelacionPagoTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CargosRelacionesPagoAuxiliar> tCC_CargosRelacionesPagoAuxiliar { get; set; }
        public virtual tCC_Clientes tCC_Clientes { get; set; }
        public virtual tCC_Cobradores tCC_Cobradores { get; set; }
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        public virtual tCT_EstadoDocumentoSRI tCT_EstadoDocumentoSRI { get; set; }
        public virtual tCG_GrupoComprobantes tCG_GrupoComprobantes { get; set; }
        public virtual tCG_PeriodoContable tCG_PeriodoContable { get; set; }
        public virtual tGN_TiposDocumentos tGN_TiposDocumentos { get; set; }
        public virtual tCC_RelacionPago tCC_RelacionPago { get; set; }
        public virtual tCC_TiposCobros tCC_TiposCobros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGN_FormastGN_Formass_tCC_DescargosCabRelacionPagoTemptCC_DescargosCabsRelacionCobrosAux> tGN_FormastGN_Formass_tCC_DescargosCabRelacionPagoTemptCC_DescargosCabsRelacionCobrosAux { get; set; }
    }
}
