//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_CajaIngresoDepositoTransferenciaRelacionPagoTemp
    {
        public int IdCajaIngresoDeposito { get; set; }
        public int IdDescargoCab { get; set; }
        public Nullable<int> IdCaja { get; set; }
        public string NumeroDeposito { get; set; }
        public Nullable<bool> EsDepositoDefinitivo { get; set; }
        public int IdFormaPagoSRI { get; set; }
        public int IdBancoCCQ { get; set; }
        public string Referencia { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime FechaValor { get; set; }
        public string Tipo { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tCC_Caja tCC_Caja { get; set; }
        public virtual tGN_BancosCCQ tGN_BancosCCQ { get; set; }
        public virtual tCT_FormasPagoSRI tCT_FormasPagoSRI { get; set; }
        public virtual tCC_DescargosCabRelacionPagoTemp tCC_DescargosCabRelacionPagoTemp { get; set; }
    }
}
