//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_AsientosXCruces
    {
        public int IdCruceAsiento { get; set; }
        public Nullable<int> IdCruceDocumentos { get; set; }
        public Nullable<int> IdAsientoContableCab { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdPeriodoContable { get; set; }
        public Nullable<int> IdGrupoComprobante { get; set; }
        public Nullable<long> NumeroComprobante { get; set; }
        public Nullable<decimal> TotalDebito { get; set; }
        public Nullable<decimal> TotalCredito { get; set; }
        public Nullable<int> IdEstadoCruce { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tCC_CruceDocumentos tCC_CruceDocumentos { get; set; }
        public virtual tCG_AsientosContableCab tCG_AsientosContableCab { get; set; }
        public virtual tCG_GrupoComprobantes tCG_GrupoComprobantes { get; set; }
        public virtual tCG_PeriodoContable tCG_PeriodoContable { get; set; }
        public virtual tCT_EstadoCruceDocumento tCT_EstadoCruceDocumento { get; set; }
        public virtual tGN_Empresas tGN_Empresas { get; set; }
    }
}
