//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_TempCargosTarjetas
    {
        public int IdTempCargosTarjetas { get; set; }
        public string CodigoSocio { get; set; }
        public string Identificacion { get; set; }
        public string Cliente { get; set; }
        public string Tarjeta { get; set; }
        public string FechaEmision { get; set; }
        public string NumeroDocumento { get; set; }
        public string TipoDocumentoCargo { get; set; }
        public string NumeroDocumentoDescargo { get; set; }
        public string TipoDocumentoDescargo { get; set; }
        public string Comprobante { get; set; }
        public string NumeroComprobante { get; set; }
        public string Recap { get; set; }
        public string NumeroVoucher { get; set; }
        public string TipoCredito { get; set; }
        public Nullable<decimal> Interes { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string Estado { get; set; }
        public string Facturas { get; set; }
    }
}
