//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_DescargosCab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCC_DescargosCab()
        {
            this.tCC_AsientosXDescargos = new HashSet<tCC_AsientosXDescargos>();
            this.tCC_AsientosXDescargosDevolucionesParcialesCAM = new HashSet<tCC_AsientosXDescargosDevolucionesParcialesCAM>();
            this.tCC_CajaIngresoCheque = new HashSet<tCC_CajaIngresoCheque>();
            this.tCC_CajaIngresoChequeGarantia = new HashSet<tCC_CajaIngresoChequeGarantia>();
            this.tCC_CajaIngresoDepositoTransferencia = new HashSet<tCC_CajaIngresoDepositoTransferencia>();
            this.tCC_CajaIngresoEfectivo = new HashSet<tCC_CajaIngresoEfectivo>();
            this.tCC_CajaIngresoRetenciones = new HashSet<tCC_CajaIngresoRetenciones>();
            this.tCC_CajaIngresoTarjetaCredito = new HashSet<tCC_CajaIngresoTarjetaCredito>();
            this.tCC_CargosRelacionesPagoAuxiliar = new HashSet<tCC_CargosRelacionesPagoAuxiliar>();
            this.tCC_CruceDocumentos = new HashSet<tCC_CruceDocumentos>();
            this.tCC_DescargosDet = new HashSet<tCC_DescargosDet>();
            this.tCC_TemporalCruceDoc = new HashSet<tCC_TemporalCruceDoc>();
            this.tCC_TempTransaccionesComerciales = new HashSet<tCC_TempTransaccionesComerciales>();
            this.tGS_Cuotas = new HashSet<tGS_Cuotas>();
        }
    
        public int IdDescargoCab { get; set; }
        public Nullable<int> IdAsientoContableCab { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public int IdTipoDocumento { get; set; }
        public int IdEmpresa { get; set; }
        public int IdPeriodoContable { get; set; }
        public string Ambiente { get; set; }
        public string ClaveAcceso { get; set; }
        public string ContribuyenteEspecial { get; set; }
        public string DireccionEstablecimiento { get; set; }
        public string DireccionMatriz { get; set; }
        public string DireccionSucursal { get; set; }
        public string Establecimiento { get; set; }
        public string PuntoEmision { get; set; }
        public string Secuencial { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
        public string Moneda { get; set; }
        public string NumeroAutorizacion { get; set; }
        public string ObligadoContabilidad { get; set; }
        public string TipoEmision { get; set; }
        public Nullable<decimal> Propina { get; set; }
        public Nullable<decimal> SubtotalIva { get; set; }
        public Nullable<decimal> Subtotal0 { get; set; }
        public Nullable<decimal> SubtotalNoObjetoImpuesto { get; set; }
        public Nullable<decimal> TotalExcentoIva { get; set; }
        public Nullable<decimal> SubtotalSinImpuesto { get; set; }
        public Nullable<decimal> TotalDescuento { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> Ice { get; set; }
        public Nullable<decimal> Irbpnr { get; set; }
        public decimal ValorTotal { get; set; }
        public decimal Saldo { get; set; }
        public string Motivo { get; set; }
        public string InformacionAdicional { get; set; }
        public Nullable<int> IdEstadoDocumento { get; set; }
        public Nullable<int> IdGrupoComprobante { get; set; }
        public Nullable<long> NumeroComprobante { get; set; }
        public string NombreArchivo { get; set; }
        public Nullable<int> NumeroOrden { get; set; }
        public string ReferenciaBanco { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> IdBancoCCQ { get; set; }
        public Nullable<int> IdTarjetaCredito { get; set; }
        public Nullable<long> IdRelacionPago { get; set; }
        public Nullable<int> IdTipoCobro { get; set; }
        public Nullable<int> IdCaja { get; set; }
        public string NumeroDeposito { get; set; }
        public Nullable<bool> EsDepositoDefinitivo { get; set; }
        public Nullable<int> IdEstadoDOCE { get; set; }
        public string MensajeDOCE { get; set; }
        public bool EnviarAlDoce { get; set; }
        public string NumeroCaso { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<int> IdHistorialCierreCaja { get; set; }
        public Nullable<int> IdTipoDocumentoModificado { get; set; }
        public string NumeroDocumentoModificado { get; set; }
        public Nullable<System.DateTime> FechaEmisionDocSustento { get; set; }
        public Nullable<System.DateTime> FechaEnvioDOCE { get; set; }
        public Nullable<System.DateTime> FechaRespuestaDOCE { get; set; }
        public Nullable<int> IdCuota { get; set; }
        public Nullable<bool> Contabilizado { get; set; }
        public Nullable<int> IdPlanCuentaEmpresaSaldo { get; set; }
        public Nullable<int> idnotacredito { get; set; }
        public Nullable<int> idtarjetaliquidacion { get; set; }
        public string cod_comp { get; set; }
        public Nullable<int> num_comp { get; set; }
        public Nullable<System.Guid> IdProceso { get; set; }
        public Nullable<int> IdCargoCabDebito { get; set; }
        public string FacturaReferenciaCam { get; set; }
        public Nullable<int> IdCobrador { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdCargoCabAsociadoRetencion { get; set; }
        public Nullable<int> IdAsientoContableCabAnulacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<int> IdPlanCuentaEmpresaIngresoAnulacion { get; set; }
        public Nullable<bool> EsDevolucion { get; set; }
        public Nullable<int> IdCobro { get; set; }
        public Nullable<bool> @fixed { get; set; }
        public Nullable<decimal> SaldoDevolverAnularCAM { get; set; }
        public string ObservacionSaldoDevolverAnularCAM { get; set; }
        public Nullable<int> IdCargoCab { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_AsientosXDescargos> tCC_AsientosXDescargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_AsientosXDescargosDevolucionesParcialesCAM> tCC_AsientosXDescargosDevolucionesParcialesCAM { get; set; }
        public virtual tCC_Caja tCC_Caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CajaIngresoCheque> tCC_CajaIngresoCheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CajaIngresoChequeGarantia> tCC_CajaIngresoChequeGarantia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CajaIngresoDepositoTransferencia> tCC_CajaIngresoDepositoTransferencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CajaIngresoEfectivo> tCC_CajaIngresoEfectivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CajaIngresoRetenciones> tCC_CajaIngresoRetenciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CajaIngresoTarjetaCredito> tCC_CajaIngresoTarjetaCredito { get; set; }
        public virtual tCC_CargosCab tCC_CargosCab { get; set; }
        public virtual tCC_CargosCab tCC_CargosCab1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CargosRelacionesPagoAuxiliar> tCC_CargosRelacionesPagoAuxiliar { get; set; }
        public virtual tCC_Clientes tCC_Clientes { get; set; }
        public virtual tCC_Cobradores tCC_Cobradores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CruceDocumentos> tCC_CruceDocumentos { get; set; }
        public virtual tGN_BancosCCQ tGN_BancosCCQ { get; set; }
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        public virtual tCT_EstadoDocumentoSRI tCT_EstadoDocumentoSRI { get; set; }
        public virtual tCG_GrupoComprobantes tCG_GrupoComprobantes { get; set; }
        public virtual tCC_HistorialCierreCaja tCC_HistorialCierreCaja { get; set; }
        public virtual tCG_PlanCuentasEmpresa tCG_PlanCuentasEmpresa { get; set; }
        public virtual tCC_RelacionPago tCC_RelacionPago { get; set; }
        public virtual tCC_TiposCobros tCC_TiposCobros { get; set; }
        public virtual tCG_AsientosContableCab tCG_AsientosContableCab { get; set; }
        public virtual tCG_AsientosContableCab tCG_AsientosContableCab1 { get; set; }
        public virtual tCG_PeriodoContable tCG_PeriodoContable { get; set; }
        public virtual tCG_PlanCuentasEmpresa tCG_PlanCuentasEmpresa1 { get; set; }
        public virtual tGN_TarjetaCredito tGN_TarjetaCredito { get; set; }
        public virtual tGN_TiposDocumentos tGN_TiposDocumentos { get; set; }
        public virtual tGN_TiposDocumentos tGN_TiposDocumentos1 { get; set; }
        public virtual tNM_Empleados tNM_Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_DescargosDet> tCC_DescargosDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_TemporalCruceDoc> tCC_TemporalCruceDoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_TempTransaccionesComerciales> tCC_TempTransaccionesComerciales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_Cuotas> tGS_Cuotas { get; set; }
    }
}
