//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcc_HistoricoDescargosCab
    {
        public int IdHistoricoDescargosCab { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdDescargoCab { get; set; }
        public Nullable<int> IdTipoDocumentoCCQ { get; set; }
        public int IdTipoDocumento { get; set; }
        public Nullable<int> IdCobrador { get; set; }
        public decimal ValorTotal { get; set; }
        public decimal Saldo { get; set; }
        public Nullable<int> IdEstadoSocio { get; set; }
    }
}
