//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_CobroTarjetaDiscover
    {
        public int IdCobroTarjetaDiscover { get; set; }
        public Nullable<int> IdCargoCab { get; set; }
        public string NumeroTarjeta { get; set; }
        public string CodigoUnicoEstablecimiento { get; set; }
        public string FechaConsumo { get; set; }
        public string ValorConsumo { get; set; }
        public string ValorDiferido { get; set; }
        public string TipoMovimiento { get; set; }
        public string NumeroAutorizacion { get; set; }
        public string NumeroCuotas { get; set; }
        public string MotivoDebito { get; set; }
        public string BinCapturador { get; set; }
        public string FechaCaducidadTarjeta { get; set; }
        public string ValorIva { get; set; }
        public string TipoDiferido { get; set; }
        public string Moneda { get; set; }
        public string EspaciosLibres { get; set; }
        public string BaseIva { get; set; }
        public string BaseIvaCero { get; set; }
        public string ValorIvaCero { get; set; }
        public string NombreArchivoGenerado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    }
}
