//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_CargoCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCC_CargoCredito()
        {
            this.tGN_FormastGN_Formass_tCC_CargoCreditoftCC_CargoCreditos = new HashSet<tGN_FormastGN_Formass_tCC_CargoCreditoftCC_CargoCreditos>();
        }
    
        public int IdCargoCredito { get; set; }
        public Nullable<int> IdCargoCab { get; set; }
        public decimal Valor { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaCredito { get; set; }
        public Nullable<int> NumeroDias { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tCC_CargosCab tCC_CargosCab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGN_FormastGN_Formass_tCC_CargoCreditoftCC_CargoCreditos> tGN_FormastGN_Formass_tCC_CargoCreditoftCC_CargoCreditos { get; set; }
    }
}
