//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_CobroBancoProdubanco
    {
        public int IdCobroBancoProdubanco { get; set; }
        public Nullable<int> IdCargoCab { get; set; }
        public string TipoRegistroCabecera { get; set; }
        public string NombreEmpresaCabecera { get; set; }
        public string CuentaEmpresaCabecera { get; set; }
        public string TotalPlanillaCabecera { get; set; }
        public string FechaCabecera { get; set; }
        public string StatusCabecera { get; set; }
        public string MonedaCabecera { get; set; }
        public string TipoRegistroDetalle { get; set; }
        public string NombreCliente { get; set; }
        public string AutorizacionDebito { get; set; }
        public string CuentaCliente { get; set; }
        public string ValorTotalRecaudar { get; set; }
        public string FechaDetalle { get; set; }
        public string StatusDetalle { get; set; }
        public string MonedaDetalle { get; set; }
        public string BaseImponibleRentaServicios { get; set; }
        public string CodigoRetencionRentaServicios { get; set; }
        public string BaseImponibleRentaBienes { get; set; }
        public string CodigoRetencionRentaBienes { get; set; }
        public string BaseRetencionIvaServicios { get; set; }
        public string CodigoRetencionIvaServicios { get; set; }
        public string BaseRetencionIvaBienes { get; set; }
        public string CodigoRetencionIvaBienes { get; set; }
        public string BaseIvaCero { get; set; }
        public string BaseIce { get; set; }
        public string NombreArchivoGenerado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tCC_CargosCab tCC_CargosCab { get; set; }
    }
}
