//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_RetencionesDebitoBanco
    {
        public int IdRetencionesDebitoBanco { get; set; }
        public Nullable<int> IdAsientoContableCab { get; set; }
        public string IdentificacionEmisor { get; set; }
        public string NumeroRetencion { get; set; }
        public int IdRetencion { get; set; }
        public decimal BaseImponible { get; set; }
        public decimal PorcentajeRetencion { get; set; }
        public decimal ValorRetenido { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string NumeroAutorizacion { get; set; }
        public string Glosa { get; set; }
        public string Referencia { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public bool Procesado { get; set; }
    
        public virtual tCC_Retenciones tCC_Retenciones { get; set; }
        public virtual tCG_AsientosContableCab tCG_AsientosContableCab { get; set; }
    }
}
