//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_Retenciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCC_Retenciones()
        {
            this.tCC_CajaIngresoRetenciones = new HashSet<tCC_CajaIngresoRetenciones>();
            this.tCC_CajaIngresoRetencionesCero = new HashSet<tCC_CajaIngresoRetencionesCero>();
            this.tCC_CajaIngresoRetencionesRelacionPagoTemp = new HashSet<tCC_CajaIngresoRetencionesRelacionPagoTemp>();
            this.tCC_IngresoRetencionesXml = new HashSet<tCC_IngresoRetencionesXml>();
            this.tCC_RetencionesDebitoBanco = new HashSet<tCC_RetencionesDebitoBanco>();
        }
    
        public int IdRetencion { get; set; }
        public string CodigoSRI { get; set; }
        public decimal PorcentajeRetencion { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CajaIngresoRetenciones> tCC_CajaIngresoRetenciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CajaIngresoRetencionesCero> tCC_CajaIngresoRetencionesCero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CajaIngresoRetencionesRelacionPagoTemp> tCC_CajaIngresoRetencionesRelacionPagoTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_IngresoRetencionesXml> tCC_IngresoRetencionesXml { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_RetencionesDebitoBanco> tCC_RetencionesDebitoBanco { get; set; }
    }
}
