//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_CobroTarjetaDiners
    {
        public int IdCobroTarjetaDiners { get; set; }
        public Nullable<int> IdCargoCab { get; set; }
        public string TipoRegistroCabecera { get; set; }
        public string FechaTransmision { get; set; }
        public string NumeroRegistros { get; set; }
        public string CodigoUnicoEstablecimiento { get; set; }
        public string NombreEstablecimiento { get; set; }
        public string NumeroEnvio { get; set; }
        public string EspacionBlanco_92 { get; set; }
        public string TipoRegistroDetalle { get; set; }
        public string Filler { get; set; }
        public string NumeroTarjeta { get; set; }
        public string FechaVale { get; set; }
        public string NumeroVale { get; set; }
        public string IdentificadorTipoCredito { get; set; }
        public string NumeroAutorizacion { get; set; }
        public string ValorConsumo { get; set; }
        public string ValorIntereses { get; set; }
        public string ValorBruto { get; set; }
        public string NumeroCuotas { get; set; }
        public string TipoMoneda { get; set; }
        public string ValorIva { get; set; }
        public string CodigoTransaccionLealtad { get; set; }
        public string BaseIva { get; set; }
        public string BaseIvaCero { get; set; }
        public string ValorIvaCero { get; set; }
        public string NombreArchivoGenerado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    }
}
