//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_HistoricoCargosCab
    {
        public int IdHistoricoCargosCab { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdCargoCab { get; set; }
        public int IdTipoDocumentoCCQ { get; set; }
        public int IdCobradorEfectivo { get; set; }
        public decimal ValorTotal { get; set; }
        public decimal Saldo { get; set; }
    }
}
