//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCC_ReferenciasDebitoBanco
    {
        public int IdReferenciasDebitoBanco { get; set; }
        public Nullable<int> IdAsientoContableCab { get; set; }
        public string Referencia { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> ValorAcreditado { get; set; }
        public Nullable<decimal> ValorDebitado { get; set; }
        public bool Procesado { get; set; }
    
        public virtual tCG_AsientosContableCab tCG_AsientosContableCab { get; set; }
    }
}
