//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCEC_AnexosEventosCursos
    {
        public int IdAnexoEventoCurso { get; set; }
        public int IdEventoCursoXDictar { get; set; }
        public string Descripcion { get; set; }
        public string UrlAnexo { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string ModificadoPor { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tCEC_EventosCursosXDictar tCEC_EventosCursosXDictar { get; set; }
    }
}
