//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCEC_PoliticasPromocion
    {
        public int ID { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> CantidadParticipantes { get; set; }
        public Nullable<int> idListaPrecio { get; set; }
        public Nullable<bool> AplicaSocio { get; set; }
        public Nullable<decimal> ValorFinal { get; set; }
    
        public virtual tFT_Productos tFT_Productos { get; set; }
    }
}
