//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCEC_UbicacionesEventosCursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCEC_UbicacionesEventosCursos()
        {
            this.tCEC_EventosCursosXDictar = new HashSet<tCEC_EventosCursosXDictar>();
        }
    
        public int IdUbicacionEventoCurso { get; set; }
        public Nullable<int> IdDireccionEventoCurso { get; set; }
        public string Descripcion { get; set; }
        public string UbicacionDireccion { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string ModificadoPor { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<short> cod_aula { get; set; }
    
        public virtual tCEC_DireccionesEventosCursos tCEC_DireccionesEventosCursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCEC_EventosCursosXDictar> tCEC_EventosCursosXDictar { get; set; }
    }
}
