//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCG_Reporte_Por_Periodos
    {
        public int IdReportePorPeriodos { get; set; }
        public Nullable<int> IdPlanCuentasEmpresa { get; set; }
        public Nullable<int> HijaDe { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string CodigoPlanCuentas { get; set; }
        public string CodigoPlanCuentasMascara { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<decimal> SaldoInicialEnero { get; set; }
        public Nullable<decimal> DebitoEnero { get; set; }
        public Nullable<decimal> CreditoEnero { get; set; }
        public Nullable<decimal> SaldoFinalEnero { get; set; }
        public Nullable<decimal> SaldoInicialFebrero { get; set; }
        public Nullable<decimal> DebitoFebrero { get; set; }
        public Nullable<decimal> CreditoFebrero { get; set; }
        public Nullable<decimal> SaldoFinalFebrero { get; set; }
        public Nullable<decimal> SaldoInicialMarzo { get; set; }
        public Nullable<decimal> DebitoMarzo { get; set; }
        public Nullable<decimal> CreditoMarzo { get; set; }
        public Nullable<decimal> SaldoFinalMarzo { get; set; }
        public Nullable<decimal> SaldoInicialAbril { get; set; }
        public Nullable<decimal> DebitoAbril { get; set; }
        public Nullable<decimal> CreditoAbril { get; set; }
        public Nullable<decimal> SaldoFinalAbril { get; set; }
        public Nullable<decimal> SaldoInicialMayo { get; set; }
        public Nullable<decimal> DebitoMayo { get; set; }
        public Nullable<decimal> CreditoMayo { get; set; }
        public Nullable<decimal> SaldoFinalMayo { get; set; }
        public Nullable<decimal> SaldoInicialJunio { get; set; }
        public Nullable<decimal> DebitoJunio { get; set; }
        public Nullable<decimal> CreditoJunio { get; set; }
        public Nullable<decimal> SaldoFinalJunio { get; set; }
        public Nullable<decimal> SaldoInicialJulio { get; set; }
        public Nullable<decimal> DebitoJulio { get; set; }
        public Nullable<decimal> CreditoJulio { get; set; }
        public Nullable<decimal> SaldoFinalJulio { get; set; }
        public Nullable<decimal> SaldoInicialAgosto { get; set; }
        public Nullable<decimal> DebitoAgosto { get; set; }
        public Nullable<decimal> CreditoAgosto { get; set; }
        public Nullable<decimal> SaldoFinalAgosto { get; set; }
        public Nullable<decimal> SaldoInicialSeptiembre { get; set; }
        public Nullable<decimal> DebitoSeptiembre { get; set; }
        public Nullable<decimal> CreditoSeptiembre { get; set; }
        public Nullable<decimal> SaldoFinalSeptiembre { get; set; }
        public Nullable<decimal> SaldoInicialOctubre { get; set; }
        public Nullable<decimal> DebitoOctubre { get; set; }
        public Nullable<decimal> CreditoOctubre { get; set; }
        public Nullable<decimal> SaldoFinalOctubre { get; set; }
        public Nullable<decimal> SaldoInicialNoviembre { get; set; }
        public Nullable<decimal> DebitoNoviembre { get; set; }
        public Nullable<decimal> CreditoNoviembre { get; set; }
        public Nullable<decimal> SaldoFinalNoviembre { get; set; }
        public Nullable<decimal> SaldoInicialDiciembre { get; set; }
        public Nullable<decimal> DebitoDiciembre { get; set; }
        public Nullable<decimal> CreditoDiciembre { get; set; }
        public Nullable<decimal> SaldoFinalDiciembre { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string ColumnasVisibles { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> Secuencial { get; set; }
    }
}
