//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCG_SangriasReportes
    {
        public int IdSangria { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<int> Espacios { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
