//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCG_GrupoComprobantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCG_GrupoComprobantes()
        {
            this.ATS_Compras = new HashSet<ATS_Compras>();
            this.tCC_AsientosXCargos = new HashSet<tCC_AsientosXCargos>();
            this.tCC_AsientosXCruces = new HashSet<tCC_AsientosXCruces>();
            this.tCC_AsientosXDescargos = new HashSet<tCC_AsientosXDescargos>();
            this.tCC_AsientosXDescargosDevolucionesParcialesCAM = new HashSet<tCC_AsientosXDescargosDevolucionesParcialesCAM>();
            this.tCC_CargosCab = new HashSet<tCC_CargosCab>();
            this.tCC_DescargosCab = new HashSet<tCC_DescargosCab>();
            this.tCC_DescargosCabRelacionPagoTemp = new HashSet<tCC_DescargosCabRelacionPagoTemp>();
            this.tCC_HistorialCierreCaja = new HashSet<tCC_HistorialCierreCaja>();
            this.tCC_RelacionPago = new HashSet<tCC_RelacionPago>();
            this.tCC_TempTransaccionesComerciales = new HashSet<tCC_TempTransaccionesComerciales>();
            this.tCG_AsientosContableCab = new HashSet<tCG_AsientosContableCab>();
            this.tCG_IntAsientosContableCab = new HashSet<tCG_IntAsientosContableCab>();
            this.tCG_SecuencialesComprobantes = new HashSet<tCG_SecuencialesComprobantes>();
            this.tCP_AsientosXCargos = new HashSet<tCP_AsientosXCargos>();
            this.tCP_AsientosXCruces = new HashSet<tCP_AsientosXCruces>();
            this.tCP_AsientosXDescargos = new HashSet<tCP_AsientosXDescargos>();
            this.tCP_CargosCab = new HashSet<tCP_CargosCab>();
            this.tCP_DescargosCab = new HashSet<tCP_DescargosCab>();
            this.tGN_TiposDocumentos = new HashSet<tGN_TiposDocumentos>();
        }
    
        public int IdGrupoComprobante { get; set; }
        public int IdEmpresa { get; set; }
        public string Descripcion { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> NumeroInicial { get; set; }
        public int NumeroActual { get; set; }
        public Nullable<bool> PermiteMovimientoManual { get; set; }
        public Nullable<bool> MayorizacionAutomatica { get; set; }
        public Nullable<bool> ContabilizacionAutomatica { get; set; }
        public int FrecuenciaReinicio { get; set; }
        public string FechaUltimoReinicio { get; set; }
        public bool Estado { get; set; }
        public int IdTipoGrupoComprobante { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATS_Compras> ATS_Compras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_AsientosXCargos> tCC_AsientosXCargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_AsientosXCruces> tCC_AsientosXCruces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_AsientosXDescargos> tCC_AsientosXDescargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_AsientosXDescargosDevolucionesParcialesCAM> tCC_AsientosXDescargosDevolucionesParcialesCAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CargosCab> tCC_CargosCab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_DescargosCab> tCC_DescargosCab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_DescargosCabRelacionPagoTemp> tCC_DescargosCabRelacionPagoTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_HistorialCierreCaja> tCC_HistorialCierreCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_RelacionPago> tCC_RelacionPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_TempTransaccionesComerciales> tCC_TempTransaccionesComerciales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCG_AsientosContableCab> tCG_AsientosContableCab { get; set; }
        public virtual tCG_TipoGrupoComprobante tCG_TipoGrupoComprobante { get; set; }
        public virtual tCT_FrecuenciaReinicioPeriodo tCT_FrecuenciaReinicioPeriodo { get; set; }
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCG_IntAsientosContableCab> tCG_IntAsientosContableCab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCG_SecuencialesComprobantes> tCG_SecuencialesComprobantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_AsientosXCargos> tCP_AsientosXCargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_AsientosXCruces> tCP_AsientosXCruces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_AsientosXDescargos> tCP_AsientosXDescargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_CargosCab> tCP_CargosCab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_DescargosCab> tCP_DescargosCab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGN_TiposDocumentos> tGN_TiposDocumentos { get; set; }
    }
}
