//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCG_Reporte_Por_Periodos_Tres
    {
        public int id { get; set; }
        public string CodigoPlanCuentas { get; set; }
        public string Descripcion { get; set; }
        public string NombreCampo1 { get; set; }
        public string NombreCampo2 { get; set; }
        public string NombreCampo3 { get; set; }
        public Nullable<decimal> ValorCampo1 { get; set; }
        public Nullable<decimal> ValorCampo2 { get; set; }
        public Nullable<decimal> ValorCampo3 { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string FechaPeriodoFinal { get; set; }
        public string NombreEmpresa { get; set; }
    }
}
