//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCG_IntAsientosContableCab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCG_IntAsientosContableCab()
        {
            this.tCG_IntAsientosContableDet = new HashSet<tCG_IntAsientosContableDet>();
        }
    
        public int IdAsientoContableCab { get; set; }
        public Nullable<int> IdPeriodoContable { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public int IdGrupoComprobante { get; set; }
        public Nullable<long> NumeroComprobante { get; set; }
        public Nullable<decimal> TotalDebito { get; set; }
        public Nullable<decimal> TotalCredito { get; set; }
        public Nullable<int> IdEstadoAsiento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaComprobante { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public string Beneficiario { get; set; }
        public bool Contabilizado { get; set; }
        public string Observacion { get; set; }
        public string IdentificacionBeneficiario { get; set; }
    
        public virtual tCG_GrupoComprobantes tCG_GrupoComprobantes { get; set; }
        public virtual tCG_PeriodoContable tCG_PeriodoContable { get; set; }
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCG_IntAsientosContableDet> tCG_IntAsientosContableDet { get; set; }
    }
}
