//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCP_LiquidacionComprasImpuestosPorReembolso
    {
        public long IdImpuestoPorReembolso { get; set; }
        public int IdReembolso { get; set; }
        public int IdCargoCab { get; set; }
        public string Codigo { get; set; }
        public string CodigoPorcentaje { get; set; }
        public Nullable<decimal> Tarifa { get; set; }
        public Nullable<decimal> DescuentoAdicional { get; set; }
        public Nullable<decimal> BaseImponible { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public int IdSocio { get; set; }
        public string xtraImpuestoDescripcion { get; set; }
        public string xtraCodigoPorcentajeDescripcion { get; set; }
        public int xtraIdReembolsoPadre { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string ModificadoPor { get; set; }
        public string EstacionModificacion { get; set; }
    }
}
