//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCP_CargosCab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCP_CargosCab()
        {
            this.tCP_AnexosCargos = new HashSet<tCP_AnexosCargos>();
            this.tCP_AprobacionDePagos = new HashSet<tCP_AprobacionDePagos>();
            this.tCP_AsientosXCargos = new HashSet<tCP_AsientosXCargos>();
            this.tCP_CargosCabReembolso = new HashSet<tCP_CargosCabReembolso>();
            this.tCP_CargosDet = new HashSet<tCP_CargosDet>();
            this.tCP_ConfirmacionBancosAuxiliar = new HashSet<tCP_ConfirmacionBancosAuxiliar>();
            this.tCP_CruceDocumentos = new HashSet<tCP_CruceDocumentos>();
            this.tCP_DescargosDet = new HashSet<tCP_DescargosDet>();
            this.tCP_FallosDebitoBancos = new HashSet<tCP_FallosDebitoBancos>();
            this.tCP_FinanciamientoCargos = new HashSet<tCP_FinanciamientoCargos>();
            this.tCP_TemporalCruceDoc = new HashSet<tCP_TemporalCruceDoc>();
            this.tIV_MaestroRecepciones = new HashSet<tIV_MaestroRecepciones>();
        }
    
        public int IdCargoCab { get; set; }
        public Nullable<int> IdAsientoContableCab { get; set; }
        public int IdTipoDocumento { get; set; }
        public int IdEmpresa { get; set; }
        public int IdPeriodoContable { get; set; }
        public int IdProveedor { get; set; }
        public int IdGrupoComprobante { get; set; }
        public Nullable<int> IdSustentoSRI { get; set; }
        public Nullable<long> NumeroComprobante { get; set; }
        public string Ambiente { get; set; }
        public string ClaveAcceso { get; set; }
        public string ContribuyenteEspecial { get; set; }
        public string DireccionEstablecimiento { get; set; }
        public string DireccionMatriz { get; set; }
        public string DireccionSucursal { get; set; }
        public string Establecimiento { get; set; }
        public string PuntoEmision { get; set; }
        public string Secuencial { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string Moneda { get; set; }
        public string NumeroAutorizacion { get; set; }
        public string ObligadoContabilidad { get; set; }
        public string TipoEmision { get; set; }
        public Nullable<decimal> Propina { get; set; }
        public Nullable<decimal> SubtotalIva { get; set; }
        public Nullable<decimal> Subtotal0 { get; set; }
        public Nullable<decimal> SubtotalNoObjetoImpuesto { get; set; }
        public Nullable<decimal> TotalExcentoIva { get; set; }
        public Nullable<decimal> SubtotalSinImpuesto { get; set; }
        public Nullable<decimal> TotalDescuento { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> Ice { get; set; }
        public Nullable<decimal> Irbpnr { get; set; }
        public Nullable<int> IdRetencionRentaPropina { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string InformacionAdicional { get; set; }
        public Nullable<int> IdEstadoDocumento { get; set; }
        public Nullable<bool> EsManual { get; set; }
        public Nullable<bool> EstadoFinanciamiento { get; set; }
        public Nullable<bool> EstaEnAprobacion { get; set; }
        public Nullable<bool> GeneraRetencion { get; set; }
        public string Glosa { get; set; }
        public string NumeroCaso { get; set; }
        public Nullable<bool> NotaCreditoGenerada { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<int> idretenciones { get; set; }
        public Nullable<int> IdPlanCuentasEmpresaCXP { get; set; }
        public bool EsDocumentoCam { get; set; }
        public Nullable<bool> AprobadoParaPago { get; set; }
        public Nullable<decimal> ValorRetencionRentaPropina { get; set; }
        public Nullable<System.DateTime> FechaComprobante { get; set; }
        public Nullable<int> IdEstadoAprobacionJefeFinanciero { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaHoraAprobacion { get; set; }
        public Nullable<bool> EnviaAprobacion { get; set; }
        public string ReferenciaPresidente { get; set; }
        public string NumeroOrdenCAM { get; set; }
    
        public virtual tCG_AsientosContableCab tCG_AsientosContableCab { get; set; }
        public virtual tCG_GrupoComprobantes tCG_GrupoComprobantes { get; set; }
        public virtual tCG_PeriodoContable tCG_PeriodoContable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_AnexosCargos> tCP_AnexosCargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_AprobacionDePagos> tCP_AprobacionDePagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_AsientosXCargos> tCP_AsientosXCargos { get; set; }
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        public virtual tCP_EstadosAprobacionJefeFinanciero tCP_EstadosAprobacionJefeFinanciero { get; set; }
        public virtual tCT_EstadoDocumentoSRI tCT_EstadoDocumentoSRI { get; set; }
        public virtual tCP_Proveedores tCP_Proveedores { get; set; }
        public virtual tCP_RetencionesRenta tCP_RetencionesRenta { get; set; }
        public virtual tCP_SustentoSRI tCP_SustentoSRI { get; set; }
        public virtual tGN_TiposDocumentos tGN_TiposDocumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_CargosCabReembolso> tCP_CargosCabReembolso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_CargosDet> tCP_CargosDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_ConfirmacionBancosAuxiliar> tCP_ConfirmacionBancosAuxiliar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_CruceDocumentos> tCP_CruceDocumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_DescargosDet> tCP_DescargosDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_FallosDebitoBancos> tCP_FallosDebitoBancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_FinanciamientoCargos> tCP_FinanciamientoCargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_TemporalCruceDoc> tCP_TemporalCruceDoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tIV_MaestroRecepciones> tIV_MaestroRecepciones { get; set; }
    }
}
