//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCP_ConsecutivoArchivoBanco
    {
        public int IdConsecutivoArchivoBanco { get; set; }
        public string CodigoBanco { get; set; }
        public int Consecutivo { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
