//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCP_TemporalCruceDoc
    {
        public int IdTemporalCruceDoc { get; set; }
        public int IdProveedor { get; set; }
        public int IdTipoDocumento { get; set; }
        public Nullable<int> IdCargoCab { get; set; }
        public Nullable<int> IdDescargoCab { get; set; }
        public decimal Valor { get; set; }
        public decimal Saldo { get; set; }
        public int IdEstadoDocumento { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public string UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tCP_CargosCab tCP_CargosCab { get; set; }
        public virtual tCP_DescargosCab tCP_DescargosCab { get; set; }
        public virtual tCP_Proveedores tCP_Proveedores { get; set; }
        public virtual tCT_EstadoDocumentoSRI tCT_EstadoDocumentoSRI { get; set; }
        public virtual tGN_TiposDocumentos tGN_TiposDocumentos { get; set; }
    }
}
