//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCP_Temporal_Descargos_ConfirmacionBancos
    {
        public int IdTemporalDescargos { get; set; }
        public Nullable<int> Id_tCP_Descargos { get; set; }
        public string IdCargoCab { get; set; }
        public string NumeroOrdenPago { get; set; }
        public Nullable<int> IdBancoCCQ { get; set; }
        public Nullable<System.DateTime> FechaTransaccion { get; set; }
        public string DescripcionReferencia { get; set; }
        public Nullable<decimal> ValorRetorno { get; set; }
    }
}
