//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCP_OrdenesPagos
    {
        public int IdOrdenPago { get; set; }
        public Nullable<int> IdAprobacionPago { get; set; }
        public Nullable<int> SecuencialCobro { get; set; }
        public Nullable<int> NumeroOrden { get; set; }
        public Nullable<int> IdCargoCab { get; set; }
        public Nullable<int> IdBancoCCQ { get; set; }
        public Nullable<decimal> ValorPagar { get; set; }
        public string FormaPago { get; set; }
        public string TipoCuenta { get; set; }
        public string NumeroCuenta { get; set; }
        public Nullable<System.DateTime> FechaOrden { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string ArchivoTxt { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tGN_BancosCCQ tGN_BancosCCQ { get; set; }
    }
}
