//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCP_RetencionesIVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCP_RetencionesIVA()
        {
            this.tCC_TiposContribuyentes = new HashSet<tCC_TiposContribuyentes>();
            this.tCC_TiposContribuyentes1 = new HashSet<tCC_TiposContribuyentes>();
            this.tCP_CargosDet = new HashSet<tCP_CargosDet>();
            this.tCP_TiposContribuyentes = new HashSet<tCP_TiposContribuyentes>();
            this.tCP_TiposContribuyentes1 = new HashSet<tCP_TiposContribuyentes>();
        }
    
        public int IdRetencionIva { get; set; }
        public Nullable<int> CodigoSRI { get; set; }
        public Nullable<decimal> PorcentajeRetencion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_TiposContribuyentes> tCC_TiposContribuyentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_TiposContribuyentes> tCC_TiposContribuyentes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_CargosDet> tCP_CargosDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_TiposContribuyentes> tCP_TiposContribuyentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_TiposContribuyentes> tCP_TiposContribuyentes1 { get; set; }
    }
}
