//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCP_ArchivoBancoAnticipado
    {
        public int IdArchivoBancoAnticipado { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdBancoCCQ { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<bool> ArchivoGenerado { get; set; }
        public Nullable<bool> EstadoPagado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tGN_BancosCCQ tGN_BancosCCQ { get; set; }
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        public virtual tCP_Proveedores tCP_Proveedores { get; set; }
    }
}
