//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCP_FinanciamientoCargos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCP_FinanciamientoCargos()
        {
            this.tCP_AprobacionDePagos = new HashSet<tCP_AprobacionDePagos>();
        }
    
        public int IdFinanciamientoCargos { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdCargoCab { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int Plazo { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public string UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_AprobacionDePagos> tCP_AprobacionDePagos { get; set; }
        public virtual tCP_CargosCab tCP_CargosCab { get; set; }
        public virtual tGN_Empresas tGN_Empresas { get; set; }
    }
}
