//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCT_CategoriaJerarquica1_2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCT_CategoriaJerarquica1_2()
        {
            this.tCC_CargosCab = new HashSet<tCC_CargosCab>();
            this.tCC_TempTransaccionesComerciales = new HashSet<tCC_TempTransaccionesComerciales>();
            this.tCG_PlanCuentasEmpresa = new HashSet<tCG_PlanCuentasEmpresa>();
            this.tRP_PresupuestoVentas = new HashSet<tRP_PresupuestoVentas>();
            this.tFT_Productos = new HashSet<tFT_Productos>();
            this.tRP_VentasDiariasArea = new HashSet<tRP_VentasDiariasArea>();
        }
    
        public int IdCategoriaJerarquica1_2 { get; set; }
        public string CategoriaJerarquica1_2 { get; set; }
        public Nullable<int> IdCategoriaJerarquica1_1 { get; set; }
        public Nullable<int> MetodoProyeccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CargosCab> tCC_CargosCab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_TempTransaccionesComerciales> tCC_TempTransaccionesComerciales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCG_PlanCuentasEmpresa> tCG_PlanCuentasEmpresa { get; set; }
        public virtual tCT_CategoriaJerarquica1_1 tCT_CategoriaJerarquica1_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRP_PresupuestoVentas> tRP_PresupuestoVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFT_Productos> tFT_Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRP_VentasDiariasArea> tRP_VentasDiariasArea { get; set; }
    }
}
