//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempo_delete_correos_comex
    {
        public int Id { get; set; }
        public string CorreoElectronico { get; set; }
        public Nullable<bool> Estado1 { get; set; }
    }
}
