//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempo_delete_backup_tGN_Personas_antes_update_representante_legal_vbohorques_2023_03
    {
        public int IdSocio { get; set; }
        public int CodigoSocio { get; set; }
        public int IdEstadoSocio { get; set; }
        public int IdEmpresa { get; set; }
        public int IdPersona { get; set; }
        public Nullable<int> IdMedioPago { get; set; }
        public Nullable<int> IdNotariaSocio { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<int> IdAsesor { get; set; }
        public Nullable<int> IdCobrador { get; set; }
        public Nullable<int> IdCobradorSecundario { get; set; }
        public Nullable<int> IdConsorcio { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> IdTipoCuenta { get; set; }
        public Nullable<int> IdRepresentanteLegal { get; set; }
        public Nullable<int> IdCargoRepresentanteLegal { get; set; }
        public Nullable<int> IdTamanoSocio { get; set; }
        public string NumeroCuenta { get; set; }
        public Nullable<int> IdTarjetaCredito { get; set; }
        public string NombreTitular { get; set; }
        public string NumeroTarjetaCredito { get; set; }
        public Nullable<System.DateTime> FechaCaducidadTarjeta { get; set; }
        public Nullable<int> IdFormaPagoSRI { get; set; }
        public string NombreComercial { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<System.DateTime> FechaConstitucion { get; set; }
        public Nullable<decimal> ValorCapital { get; set; }
        public Nullable<decimal> ValorCuotaIngreso { get; set; }
        public decimal ValorCuota { get; set; }
        public Nullable<decimal> ValorDescuentoAcuerdo { get; set; }
        public Nullable<int> IdFrecuenciaGeneracionCuota { get; set; }
        public string CodigoRegistroMercantil { get; set; }
        public Nullable<System.DateTime> FechaInscripcionRegistroMercantil { get; set; }
        public string Categoria { get; set; }
        public Nullable<decimal> ValorActivos { get; set; }
        public Nullable<int> NumeroEmpleados { get; set; }
        public Nullable<decimal> ValorVentas { get; set; }
        public Nullable<System.DateTime> FechaAfiliacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaGeneracionCuota { get; set; }
        public Nullable<System.DateTime> FechaInicioDebito { get; set; }
        public Nullable<bool> FacturacionRetrasada { get; set; }
        public string CorreosElectronicos { get; set; }
        public string Telefonos { get; set; }
        public Nullable<int> IdParroquiaMatriz { get; set; }
        public Nullable<int> IdDireccionMatriz { get; set; }
        public Nullable<int> CuotasDebe { get; set; }
        public Nullable<decimal> ValorCuotaDebe { get; set; }
        public string Direcciones { get; set; }
        public string OrdenCompraProximaFactura { get; set; }
        public Nullable<bool> NoSuspender { get; set; }
        public string Macrosector { get; set; }
        public string EstadoNotificacionBienvenida { get; set; }
        public Nullable<System.DateTime> FechaNotificacionBienvenida { get; set; }
        public Nullable<int> IdGrupoAfinidad { get; set; }
        public Nullable<decimal> ValorUtilidad { get; set; }
        public Nullable<bool> EsExportador { get; set; }
        public Nullable<bool> EsImportador { get; set; }
        public Nullable<int> CodigoSocioPadre { get; set; }
        public bool ExcluidoParaFacturacionSocial { get; set; }
        public byte IdMesEmisionBimestral { get; set; }
        public int MesesCuota { get; set; }
        public int NumeroCuotas { get; set; }
        public decimal PorcentajeDescuento { get; set; }
    }
}
