//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFT_FacturaCab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tFT_FacturaCab()
        {
            this.tFT_FacturaCabFormasPago = new HashSet<tFT_FacturaCabFormasPago>();
            this.tFT_FacturaDet = new HashSet<tFT_FacturaDet>();
        }
    
        public long IdFactura { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<decimal> TotalDescuento { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public string Establecimiento { get; set; }
        public string PuntoEmision { get; set; }
        public string Secuencial { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdTipoIdentificacion { get; set; }
        public string IdentificacionComprador { get; set; }
        public string CorreoElectronicoComprador { get; set; }
        public string DireccionComprador { get; set; }
        public Nullable<decimal> SubTotal14PorCiento { get; set; }
        public Nullable<decimal> Subtotal0PorCiento { get; set; }
        public Nullable<decimal> SubtotalNoObjetoIva { get; set; }
        public Nullable<decimal> SubtotalExcentoIva { get; set; }
        public Nullable<decimal> SubtotalSinImpuestos { get; set; }
        public Nullable<decimal> ValorIVA { get; set; }
        public Nullable<decimal> ValorICE { get; set; }
        public Nullable<decimal> ValorIRBPNR { get; set; }
        public Nullable<decimal> ValorPropina { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tCC_Clientes tCC_Clientes { get; set; }
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        public virtual tGN_TiposIdentificacion tGN_TiposIdentificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFT_FacturaCabFormasPago> tFT_FacturaCabFormasPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFT_FacturaDet> tFT_FacturaDet { get; set; }
    }
}
