//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFT_CuotasSociales
    {
        public long IdCuotasSociales { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<System.DateTime> FechaEmisionOriginal { get; set; }
        public Nullable<System.DateTime> FechaEmisionUltima { get; set; }
        public string IdTipoCuota { get; set; }
        public Nullable<decimal> ValorCuota { get; set; }
        public Nullable<decimal> SaldoCuota { get; set; }
        public Nullable<bool> EstadoCuota { get; set; }
        public Nullable<int> AnioEmision { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public Nullable<int> NumeroPeriodo { get; set; }
        public Nullable<long> IdFactura { get; set; }
    }
}
