//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFT_CuotasSociales
    {
        public long IdCuotasSociales { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<System.DateTime> FechaEmisionOriginal { get; set; }
        public Nullable<System.DateTime> FechaEmisionUltima { get; set; }
        public string IdTipoCuota { get; set; }
        public Nullable<decimal> ValorCuota { get; set; }
        public Nullable<decimal> SaldoCuota { get; set; }
        public Nullable<bool> EstadoCuota { get; set; }
        public Nullable<int> AnioEmision { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public Nullable<int> NumeroPeriodo { get; set; }
        public Nullable<long> IdFactura { get; set; }
    }
}
