//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGN_ContactoPersona_Suscripcion_Temporal
    {
        public int IdContactoPersona { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> IdMedioContacto { get; set; }
        public string Contacto { get; set; }
        public string NombresApellidosNoSocios { get; set; }
        public string Identificacion { get; set; }
        public Nullable<int> CodigoSocio { get; set; }
        public string Telefono { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> FechaToken { get; set; }
        public bool Estado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tGN_MediosContactos tGN_MediosContactos { get; set; }
        public virtual tGN_Personas tGN_Personas { get; set; }
    }
}
