//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGN_HistoricoContactoPersona
    {
        public int IdHistoricoContactoPersona { get; set; }
        public int IdContactoPersona { get; set; }
        public int IdCatEvento { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Info { get; set; }
        public string Ip { get; set; }
        public string ValorPrevio { get; set; }
        public string ValorNuevo { get; set; }
    
        public virtual CatEvento CatEvento { get; set; }
        public virtual tGN_ContactoPersona tGN_ContactoPersona { get; set; }
    }
}
