//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGN_InformacionesAdicionalesDocumentos
    {
        public int IdInformacionAdicionalDocumento { get; set; }
        public int IdEmpresa { get; set; }
        public string CodigoDocumentoSRI { get; set; }
        public string Codigo { get; set; }
        public string Llave { get; set; }
        public string Descripcion { get; set; }
        public string Valor { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
        public Nullable<int> OrdenSecuencial { get; set; }
        public string TablaOrigenDato { get; set; }
        public string CampoTablaOrigenDato { get; set; }
    
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        public virtual tGN_TablasSistema tGN_TablasSistema { get; set; }
    }
}
