//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGN_Empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tGN_Empresas()
        {
            this.tNM_Areas = new HashSet<tNM_Areas>();
            this.tNM_BasesCalculadas = new HashSet<tNM_BasesCalculadas>();
            this.tNM_CalendarioNominas = new HashSet<tNM_CalendarioNominas>();
            this.tNM_Colaboradores = new HashSet<tNM_Colaboradores>();
            this.tNM_Conceptos = new HashSet<tNM_Conceptos>();
            this.tNM_Departamentos = new HashSet<tNM_Departamentos>();
            this.tNM_Empleados = new HashSet<tNM_Empleados>();
            this.tNM_FormularioGP = new HashSet<tNM_FormularioGP>();
        }
    
        public int IdEmpresa { get; set; }
        public string Descripcion { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> TipoIdRepresentanteLegal { get; set; }
        public string IdRepresentanteLegal { get; set; }
        public string NombreRepresentanteLegal { get; set; }
        public string IdFiscal { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> TipoIdContador { get; set; }
        public string IdContador { get; set; }
        public Nullable<bool> ProduccionSRI { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public string Nombre { get; set; }
        public string RepresentanteLegal { get; set; }
        public string RUC { get; set; }
        public string NombreContador { get; set; }
        public Nullable<int> IdTipoEmpresa { get; set; }
        public Nullable<int> IdSocioDoce { get; set; }
        public Nullable<int> IdPeriodoUltimaGeneracionCuotas { get; set; }
        public Nullable<bool> EstaPausadoServiciosDOCE { get; set; }
        public string Firma1 { get; set; }
        public string Firma2 { get; set; }
        public Nullable<bool> MenuWeb { get; set; }
        public string UrlLogo { get; set; }
        public Nullable<int> ContribuyenteEspecial { get; set; }
        public string ObligadoContabilidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_Areas> tNM_Areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_BasesCalculadas> tNM_BasesCalculadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_CalendarioNominas> tNM_CalendarioNominas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_Colaboradores> tNM_Colaboradores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_Conceptos> tNM_Conceptos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_Departamentos> tNM_Departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_Empleados> tNM_Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_FormularioGP> tNM_FormularioGP { get; set; }
    }
}
