//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGN_TiposImpuestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tGN_TiposImpuestos()
        {
            this.tCC_CargosDet = new HashSet<tCC_CargosDet>();
            this.tCC_CargosDet1 = new HashSet<tCC_CargosDet>();
            this.tCC_CargosDet2 = new HashSet<tCC_CargosDet>();
            this.tCC_DescargosDet = new HashSet<tCC_DescargosDet>();
            this.tCC_DescargosDet1 = new HashSet<tCC_DescargosDet>();
            this.tCC_DescargosDet2 = new HashSet<tCC_DescargosDet>();
            this.tCP_CargosDet = new HashSet<tCP_CargosDet>();
            this.tCP_CargosDet1 = new HashSet<tCP_CargosDet>();
            this.tCP_CargosDet2 = new HashSet<tCP_CargosDet>();
            this.tCP_DescargosDet = new HashSet<tCP_DescargosDet>();
            this.tCP_DescargosDet1 = new HashSet<tCP_DescargosDet>();
            this.tCP_DescargosDet2 = new HashSet<tCP_DescargosDet>();
            this.tFT_Productos = new HashSet<tFT_Productos>();
            this.tFT_Productos1 = new HashSet<tFT_Productos>();
            this.tGN_TiposDocumentos = new HashSet<tGN_TiposDocumentos>();
            this.tGN_TiposDocumentos1 = new HashSet<tGN_TiposDocumentos>();
            this.tGN_TiposDocumentos2 = new HashSet<tGN_TiposDocumentos>();
            this.tGN_TiposDocumentos3 = new HashSet<tGN_TiposDocumentos>();
        }
    
        public int IdTipoImpuesto { get; set; }
        public Nullable<int> IdPlanCuentasEmpresa { get; set; }
        public Nullable<int> CodigoImpuesto { get; set; }
        public Nullable<int> CodigoPorcentaje { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public string Descripcion { get; set; }
        public Nullable<short> Condicion { get; set; }
        public string TipoImpuesto { get; set; }
        public Nullable<System.DateTime> FechaVigencia { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CargosDet> tCC_CargosDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CargosDet> tCC_CargosDet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CargosDet> tCC_CargosDet2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_DescargosDet> tCC_DescargosDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_DescargosDet> tCC_DescargosDet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_DescargosDet> tCC_DescargosDet2 { get; set; }
        public virtual tCG_PlanCuentasEmpresa tCG_PlanCuentasEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_CargosDet> tCP_CargosDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_CargosDet> tCP_CargosDet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_CargosDet> tCP_CargosDet2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_DescargosDet> tCP_DescargosDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_DescargosDet> tCP_DescargosDet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_DescargosDet> tCP_DescargosDet2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFT_Productos> tFT_Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFT_Productos> tFT_Productos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGN_TiposDocumentos> tGN_TiposDocumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGN_TiposDocumentos> tGN_TiposDocumentos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGN_TiposDocumentos> tGN_TiposDocumentos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGN_TiposDocumentos> tGN_TiposDocumentos3 { get; set; }
    }
}
