//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGN_Formas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tGN_Formas()
        {
            this.tGN_FormastGN_Formass_tCC_CajaIngresoChequeftCC_CajaIngresoCheques = new HashSet<tGN_FormastGN_Formass_tCC_CajaIngresoChequeftCC_CajaIngresoCheques>();
            this.tGN_FormastGN_Formass_tCC_CajaIngresoDepositoTransferenciatCC_CajaIngresoDepositoTransferencias = new HashSet<tGN_FormastGN_Formass_tCC_CajaIngresoDepositoTransferenciatCC_CajaIngresoDepositoTransferencias>();
            this.tGN_FormastGN_Formass_tCC_CajaIngresoEfectivotCC_CajaIngresoEfectivos = new HashSet<tGN_FormastGN_Formass_tCC_CajaIngresoEfectivotCC_CajaIngresoEfectivos>();
            this.tGN_FormastGN_Formass_tCC_CajaIngresoRetencionesftCC_CajaIngresoRetenciones = new HashSet<tGN_FormastGN_Formass_tCC_CajaIngresoRetencionesftCC_CajaIngresoRetenciones>();
            this.tGN_FormastGN_Formass_tCC_CajaIngresoTarjetaCreditoftCC_CajaIngresoTarjetaCreditos = new HashSet<tGN_FormastGN_Formass_tCC_CajaIngresoTarjetaCreditoftCC_CajaIngresoTarjetaCreditos>();
            this.tGN_FormastGN_Formass_tCC_CargoCreditoftCC_CargoCreditos = new HashSet<tGN_FormastGN_Formass_tCC_CargoCreditoftCC_CargoCreditos>();
            this.tGN_FormastGN_Formass_tCC_DescargosCabRelacionPagoTemptCC_DescargosCabsRelacionCobrosAux = new HashSet<tGN_FormastGN_Formass_tCC_DescargosCabRelacionPagoTemptCC_DescargosCabsRelacionCobrosAux>();
        }
    
        public int IdForma { get; set; }
        public string Vista { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<System.Guid> Document { get; set; }
        public Nullable<int> IdCaja { get; set; }
        public Nullable<int> IdBancoCCQCierre { get; set; }
        public Nullable<int> IdClienteCuotas { get; set; }
    
        public virtual tCC_Clientes tCC_Clientes { get; set; }
        public virtual tGN_BancosCCQ tGN_BancosCCQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGN_FormastGN_Formass_tCC_CajaIngresoChequeftCC_CajaIngresoCheques> tGN_FormastGN_Formass_tCC_CajaIngresoChequeftCC_CajaIngresoCheques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGN_FormastGN_Formass_tCC_CajaIngresoDepositoTransferenciatCC_CajaIngresoDepositoTransferencias> tGN_FormastGN_Formass_tCC_CajaIngresoDepositoTransferenciatCC_CajaIngresoDepositoTransferencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGN_FormastGN_Formass_tCC_CajaIngresoEfectivotCC_CajaIngresoEfectivos> tGN_FormastGN_Formass_tCC_CajaIngresoEfectivotCC_CajaIngresoEfectivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGN_FormastGN_Formass_tCC_CajaIngresoRetencionesftCC_CajaIngresoRetenciones> tGN_FormastGN_Formass_tCC_CajaIngresoRetencionesftCC_CajaIngresoRetenciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGN_FormastGN_Formass_tCC_CajaIngresoTarjetaCreditoftCC_CajaIngresoTarjetaCreditos> tGN_FormastGN_Formass_tCC_CajaIngresoTarjetaCreditoftCC_CajaIngresoTarjetaCreditos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGN_FormastGN_Formass_tCC_CargoCreditoftCC_CargoCreditos> tGN_FormastGN_Formass_tCC_CargoCreditoftCC_CargoCreditos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGN_FormastGN_Formass_tCC_DescargosCabRelacionPagoTemptCC_DescargosCabsRelacionCobrosAux> tGN_FormastGN_Formass_tCC_DescargosCabRelacionPagoTemptCC_DescargosCabsRelacionCobrosAux { get; set; }
    }
}
