//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGS_Atenciones
    {
        public int IdAtencion { get; set; }
        public int IdProductoServicio { get; set; }
        public int IdTipoContacto { get; set; }
        public Nullable<int> IdTipoGestion { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdCaso { get; set; }
        public Nullable<System.DateTime> FechaSeguimiento { get; set; }
        public int FuncionarioAtencion { get; set; }
        public string Nombre { get; set; }
        public string Identificacion { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tCC_Clientes tCC_Clientes { get; set; }
        public virtual tGN_Personas tGN_Personas { get; set; }
        public virtual tGN_Personas tGN_Personas1 { get; set; }
        public virtual tGS_Casos tGS_Casos { get; set; }
        public virtual tGS_TiposGestionAtencion tGS_TiposGestionAtencion { get; set; }
        public virtual tGS_ProductosServicios tGS_ProductosServicios { get; set; }
        public virtual tGS_TiposContactoAtencion tGS_TiposContactoAtencion { get; set; }
    }
}
