//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGS_Socios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tGS_Socios()
        {
            this.tCC_CargosCabExtension = new HashSet<tCC_CargosCabExtension>();
            this.tCC_Clientes = new HashSet<tCC_Clientes>();
            this.tCP_Proveedores = new HashSet<tCP_Proveedores>();
            this.tGS_AnexoSocio = new HashSet<tGS_AnexoSocio>();
            this.tGS_AuditoriaSocio = new HashSet<tGS_AuditoriaSocio>();
            this.tGS_Beneficiario = new HashSet<tGS_Beneficiario>();
            this.tGS_Cuotas = new HashSet<tGS_Cuotas>();
            this.tGS_Cuotas_V2 = new HashSet<tGS_Cuotas_V2>();
            this.tGS_CuotasAfiliacion = new HashSet<tGS_CuotasAfiliacion>();
            this.tGS_HistorialAltasYBajas = new HashSet<tGS_HistorialAltasYBajas>();
            this.tGS_SocioEmpleados = new HashSet<tGS_SocioEmpleados>();
            this.tGS_SocioEmpleados1 = new HashSet<tGS_SocioEmpleados>();
            this.tGS_SocioNucleo = new HashSet<tGS_SocioNucleo>();
            this.tGS_SociosActividadesCIIU = new HashSet<tGS_SociosActividadesCIIU>();
            this.tGS_SociosPreregistro = new HashSet<tGS_SociosPreregistro>();
            this.tGS_SociosPreregistro1 = new HashSet<tGS_SociosPreregistro>();
            this.tGS_SolicitudCuotaAnticipada = new HashSet<tGS_SolicitudCuotaAnticipada>();
        }
    
        public int IdSocio { get; set; }
        public int CodigoSocio { get; set; }
        public int IdEstadoSocio { get; set; }
        public int IdEmpresa { get; set; }
        public int IdPersona { get; set; }
        public Nullable<int> IdMedioPago { get; set; }
        public Nullable<int> IdNotariaSocio { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<int> IdAsesor { get; set; }
        public Nullable<int> IdCobrador { get; set; }
        public Nullable<int> IdCobradorSecundario { get; set; }
        public Nullable<int> IdConsorcio { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> IdTipoCuenta { get; set; }
        public Nullable<int> IdRepresentanteLegal { get; set; }
        public Nullable<int> IdCargoRepresentanteLegal { get; set; }
        public Nullable<int> IdTamanoSocio { get; set; }
        public string NumeroCuenta { get; set; }
        public Nullable<int> IdTarjetaCredito { get; set; }
        public string NombreTitular { get; set; }
        public string NumeroTarjetaCredito { get; set; }
        public Nullable<System.DateTime> FechaCaducidadTarjeta { get; set; }
        public Nullable<int> IdFormaPagoSRI { get; set; }
        public string NombreComercial { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<System.DateTime> FechaConstitucion { get; set; }
        public Nullable<decimal> ValorCapital { get; set; }
        public Nullable<decimal> ValorCuotaIngreso { get; set; }
        public decimal ValorCuota { get; set; }
        public Nullable<decimal> ValorDescuentoAcuerdo { get; set; }
        public Nullable<int> IdFrecuenciaGeneracionCuota { get; set; }
        public string CodigoRegistroMercantil { get; set; }
        public Nullable<System.DateTime> FechaInscripcionRegistroMercantil { get; set; }
        public string Categoria { get; set; }
        public Nullable<decimal> ValorActivos { get; set; }
        public Nullable<int> NumeroEmpleados { get; set; }
        public Nullable<decimal> ValorVentas { get; set; }
        public Nullable<System.DateTime> FechaAfiliacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaGeneracionCuota { get; set; }
        public Nullable<System.DateTime> FechaInicioDebito { get; set; }
        public Nullable<bool> FacturacionRetrasada { get; set; }
        public string CorreosElectronicos { get; set; }
        public string Telefonos { get; set; }
        public Nullable<int> IdParroquiaMatriz { get; set; }
        public Nullable<int> IdDireccionMatriz { get; set; }
        public Nullable<int> CuotasDebe { get; set; }
        public Nullable<decimal> ValorCuotaDebe { get; set; }
        public string Direcciones { get; set; }
        public string OrdenCompraProximaFactura { get; set; }
        public Nullable<bool> NoSuspender { get; set; }
        public string Macrosector { get; set; }
        public string EstadoNotificacionBienvenida { get; set; }
        public Nullable<System.DateTime> FechaNotificacionBienvenida { get; set; }
        public Nullable<int> IdGrupoAfinidad { get; set; }
        public Nullable<decimal> ValorUtilidad { get; set; }
        public Nullable<bool> EsExportador { get; set; }
        public Nullable<bool> EsImportador { get; set; }
        public Nullable<int> CodigoSocioPadre { get; set; }
        public bool ExcluidoParaFacturacionSocial { get; set; }
        public byte IdMesEmisionBimestral { get; set; }
        public int MesesCuota { get; set; }
        public int NumeroCuotas { get; set; }
        public decimal PorcentajeDescuento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_CargosCabExtension> tCC_CargosCabExtension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCC_Clientes> tCC_Clientes { get; set; }
        public virtual tCC_Cobradores tCC_Cobradores { get; set; }
        public virtual tCC_Cobradores tCC_Cobradores1 { get; set; }
        public virtual tCC_Vendedores tCC_Vendedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCP_Proveedores> tCP_Proveedores { get; set; }
        public virtual tCT_FormasPagoSRI tCT_FormasPagoSRI { get; set; }
        public virtual tGN_Bancos tGN_Bancos { get; set; }
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        public virtual tGN_EstadoSocio tGN_EstadoSocio { get; set; }
        public virtual tGN_MediosPagos tGN_MediosPagos { get; set; }
        public virtual tGN_Notaria tGN_Notaria { get; set; }
        public virtual tGN_Parroquias tGN_Parroquias { get; set; }
        public virtual tGN_Personas tGN_Personas { get; set; }
        public virtual tGN_Personas tGN_Personas1 { get; set; }
        public virtual tGN_TarjetaCredito tGN_TarjetaCredito { get; set; }
        public virtual tGN_TiposCuentas tGN_TiposCuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_AnexoSocio> tGS_AnexoSocio { get; set; }
        public virtual tGS_Asesor tGS_Asesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_AuditoriaSocio> tGS_AuditoriaSocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_Beneficiario> tGS_Beneficiario { get; set; }
        public virtual tGS_Consorcios tGS_Consorcios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_Cuotas> tGS_Cuotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_Cuotas_V2> tGS_Cuotas_V2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_CuotasAfiliacion> tGS_CuotasAfiliacion { get; set; }
        public virtual tGS_FrecuenciaGeneracionCuotas tGS_FrecuenciaGeneracionCuotas { get; set; }
        public virtual tGS_GrupoAfinidad tGS_GrupoAfinidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_HistorialAltasYBajas> tGS_HistorialAltasYBajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_SocioEmpleados> tGS_SocioEmpleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_SocioEmpleados> tGS_SocioEmpleados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_SocioNucleo> tGS_SocioNucleo { get; set; }
        public virtual tGS_TamanoSocio tGS_TamanoSocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_SociosActividadesCIIU> tGS_SociosActividadesCIIU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_SociosPreregistro> tGS_SociosPreregistro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_SociosPreregistro> tGS_SociosPreregistro1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_SolicitudCuotaAnticipada> tGS_SolicitudCuotaAnticipada { get; set; }
    }
}
