//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGS_SuscripcionContacto_Temporal
    {
        public int IdSuscripcionContacto { get; set; }
        public int IdContactoPersona { get; set; }
        public int IdTipoSuscripcion { get; set; }
        public bool ActivarEnvio { get; set; }
        public string Comentario { get; set; }
        public string eMailValidacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdCliente { get; set; }
    }
}
