//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGS_DocumentoSocios
    {
        public int IdDocumentosSocio { get; set; }
        public Nullable<int> IdSocio { get; set; }
        public Nullable<int> IdServicioDocumento { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string ResponsableEntrega { get; set; }
        public string ResponsableRecepcion { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> NumeroDeDocumentos { get; set; }
        public string EstadoDocumento { get; set; }
        public string ANombreDe { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tGS_ServicioDocumento tGS_ServicioDocumento { get; set; }
    }
}
