//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGS_TelefonosPlanSeguridad
    {
        public int IdTelefonosPlanSeguridad { get; set; }
        public int IdDireccion { get; set; }
        public string NumeroCelular { get; set; }
        public string Tipo { get; set; }
        public string CodigoRelacion { get; set; }
        public bool Estado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<int> IdCRM { get; set; }
    
        public virtual tGS_TelefonosPlanSeguridad tGS_TelefonosPlanSeguridad1 { get; set; }
        public virtual tGS_TelefonosPlanSeguridad tGS_TelefonosPlanSeguridad2 { get; set; }
    }
}
