//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGS_TemporalSocios
    {
        public int IdTemporalSocios { get; set; }
        public Nullable<int> CodigoSocio { get; set; }
        public string Identificacion { get; set; }
        public Nullable<int> IdEstadoSocio { get; set; }
        public Nullable<int> IdTipoEmpresa { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
