//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGS_TipoSuscripcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tGS_TipoSuscripcion()
        {
            this.Lpd_SuscripcionNuevoContacto = new HashSet<Lpd_SuscripcionNuevoContacto>();
            this.tGS_SuscripcionContacto = new HashSet<tGS_SuscripcionContacto>();
        }
    
        public int IdTipoSuscripcion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Automatico { get; set; }
        public string TipoEnvio { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public string Abreviacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lpd_SuscripcionNuevoContacto> Lpd_SuscripcionNuevoContacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGS_SuscripcionContacto> tGS_SuscripcionContacto { get; set; }
    }
}
