//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGS_HistorialAltasYBajas
    {
        public int IdHistorialAltaYBaja { get; set; }
        public int IdSocio { get; set; }
        public int IdMotivoAltaYBaja { get; set; }
        public System.DateTime FechaAltaOBaja { get; set; }
        public string Observacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tGS_MotivosAltasYBajas tGS_MotivosAltasYBajas { get; set; }
        public virtual tGS_Socios tGS_Socios { get; set; }
    }
}
