//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tIV_Contabilizacion
    {
        public int IdContabilizacion { get; set; }
        public int IdEmpresa { get; set; }
        public int IdTipoArticulo { get; set; }
        public int IdTipoTransaccion { get; set; }
        public Nullable<int> IdCuentaDb { get; set; }
        public Nullable<int> IdCuentaCr { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public bool NoContabilizar { get; set; }
    
        public virtual tCG_PlanCuentasEmpresa tCG_PlanCuentasEmpresa { get; set; }
        public virtual tCG_PlanCuentasEmpresa tCG_PlanCuentasEmpresa1 { get; set; }
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        public virtual tIV_TiposArticulos tIV_TiposArticulos { get; set; }
        public virtual tIV_TiposTransacciones tIV_TiposTransacciones { get; set; }
    }
}
