//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tIV_Saldos
    {
        public int IdSaldo { get; set; }
        public int IdEmpresa { get; set; }
        public int IdBodega { get; set; }
        public Nullable<int> IdPeriodoContable { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<decimal> SaldoInicial { get; set; }
        public Nullable<decimal> Entradas { get; set; }
        public Nullable<decimal> Salidas { get; set; }
        public Nullable<decimal> SaldoFinal { get; set; }
        public Nullable<decimal> CostoUnitario { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<int> IdPeriodoContableAnterior { get; set; }
    
        public virtual tCG_PeriodoContable tCG_PeriodoContable { get; set; }
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        public virtual tIV_Articulos tIV_Articulos { get; set; }
        public virtual tIV_Bodegas tIV_Bodegas { get; set; }
    }
}
