//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tIV_Fisico
    {
        public int IdFisico { get; set; }
        public int IdMaestroFisico { get; set; }
        public int IdArticulo { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Saldo { get; set; }
        public decimal CostoUnitario { get; set; }
        public decimal ValorCantidad { get; set; }
        public decimal ValorSaldo { get; set; }
        public decimal Ajuste { get; set; }
        public decimal ValorAjuste { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tIV_Articulos tIV_Articulos { get; set; }
        public virtual tIV_MaestroFisico tIV_MaestroFisico { get; set; }
    }
}
