//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNM_SolicitudPermiso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tNM_SolicitudPermiso()
        {
            this.tNM_AdjuntoSolicitudPermiso = new HashSet<tNM_AdjuntoSolicitudPermiso>();
            this.tNM_JustificacionPermiso = new HashSet<tNM_JustificacionPermiso>();
        }
    
        public int IdSolicitudPermiso { get; set; }
        public Nullable<int> IdTipoAusencia { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraFin { get; set; }
        public Nullable<decimal> NumeroHoras { get; set; }
        public Nullable<int> IdEstadoAprob { get; set; }
        public Nullable<int> Idcolaborador { get; set; }
        public Nullable<int> IdSupervisor { get; set; }
        public string RespuestaSupervisor { get; set; }
        public string RespuestaTalentoHumano { get; set; }
        public Nullable<int> DiasSolicitados { get; set; }
        public Nullable<int> IdColaboradorReemplazo { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string ModificadoPor { get; set; }
        public string EstacionModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_AdjuntoSolicitudPermiso> tNM_AdjuntoSolicitudPermiso { get; set; }
        public virtual tNM_Colaboradores tNM_Colaboradores { get; set; }
        public virtual tNM_Colaboradores tNM_Colaboradores1 { get; set; }
        public virtual tNM_EstadosFlujoAusencias tNM_EstadosFlujoAusencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_JustificacionPermiso> tNM_JustificacionPermiso { get; set; }
        public virtual tNM_TiposAusencia tNM_TiposAusencia { get; set; }
    }
}
