//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNm_BeneficiosCCQ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tNm_BeneficiosCCQ()
        {
            this.tNM_EstadosCuentaColaborador = new HashSet<tNM_EstadosCuentaColaborador>();
            this.tNM_IngresosBeneficiosColaborador = new HashSet<tNM_IngresosBeneficiosColaborador>();
        }
    
        public int IdTipoBeneficio { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_EstadosCuentaColaborador> tNM_EstadosCuentaColaborador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_IngresosBeneficiosColaborador> tNM_IngresosBeneficiosColaborador { get; set; }
    }
}
