//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNM_HistorialVacaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tNM_HistorialVacaciones()
        {
            this.tNM_DetalleVacaciones = new HashSet<tNM_DetalleVacaciones>();
            this.tNM_SolicitudVacacionesDet = new HashSet<tNM_SolicitudVacacionesDet>();
            this.tNM_VacacionesDetalle = new HashSet<tNM_VacacionesDetalle>();
        }
    
        public long IdHistorialVacaciones { get; set; }
        public Nullable<int> IdColaborador { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<decimal> DiasPendientesDisfrute { get; set; }
        public Nullable<decimal> DiasPendientesCancelar { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<decimal> IngresoPeriodo { get; set; }
        public Nullable<decimal> DiasDisfrutados { get; set; }
        public Nullable<decimal> DiasCancelados { get; set; }
        public Nullable<decimal> DiasBase { get; set; }
        public Nullable<decimal> DiasBaseAdicional { get; set; }
        public Nullable<int> FinesSemana { get; set; }
        public Nullable<decimal> DiasSolicitados { get; set; }
        public Nullable<int> FinesSemanaSolicitados { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<System.DateTime> FechaReintegro { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<int> asuetoid { get; set; }
    
        public virtual tNM_Colaboradores tNM_Colaboradores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_DetalleVacaciones> tNM_DetalleVacaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_SolicitudVacacionesDet> tNM_SolicitudVacacionesDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNM_VacacionesDetalle> tNM_VacacionesDetalle { get; set; }
    }
}
