//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNM_ConceptosGlobales
    {
        public long IdConceptoGlobal { get; set; }
        public Nullable<int> IdCalendarioNomina { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public Nullable<decimal> Unidades { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tNM_CalendarioNominas tNM_CalendarioNominas { get; set; }
        public virtual tNM_Conceptos tNM_Conceptos { get; set; }
    }
}
