//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNM_Declaracion13
    {
        public int IdDeclaracion13 { get; set; }
        public int IdCalendarioNomina { get; set; }
        public string Identificacion { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Genero { get; set; }
        public string Ocupacion { get; set; }
        public Nullable<int> DiasLaborados { get; set; }
        public string TipoPago { get; set; }
        public string JornadaParcial { get; set; }
        public string HorasSemanales { get; set; }
        public string PoseeDiscapacidad { get; set; }
        public string FechaJubilacion { get; set; }
        public string ValorRetencion { get; set; }
        public string Mensualiza13 { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<decimal> TotalGanado { get; set; }
    
        public virtual tNM_CalendarioNominas tNM_CalendarioNominas { get; set; }
    }
}
