//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNM_EstadosCuentaColaborador
    {
        public int IdEstadoCuenta { get; set; }
        public Nullable<int> IdTipoBeneficio { get; set; }
        public Nullable<int> IdColaborador { get; set; }
        public Nullable<int> IdTipoEstadoCuenta { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdReferencia { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string ModificadoPor { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tNm_BeneficiosCCQ tNm_BeneficiosCCQ { get; set; }
        public virtual tNM_Colaboradores tNM_Colaboradores { get; set; }
        public virtual tNM_TiposEstadoCuenta tNM_TiposEstadoCuenta { get; set; }
    }
}
