//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNM_DatosBiometrico
    {
        public int IdDatosBiometrico { get; set; }
        public Nullable<int> IdBiometrico { get; set; }
        public Nullable<int> IdColaborador { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<long> HoraEntrada { get; set; }
        public Nullable<long> HoraSAlmuerzo { get; set; }
        public Nullable<long> HoraEAlmuerzo { get; set; }
        public Nullable<long> TiempoAlmuerzo { get; set; }
        public Nullable<long> HoraSalida { get; set; }
        public Nullable<long> HoraEntradaT { get; set; }
        public Nullable<long> HoraSalidaT { get; set; }
        public Nullable<long> TiempoAlmuerzoT { get; set; }
        public Nullable<long> RetrasoEntrada { get; set; }
        public Nullable<long> AdelantoSalida { get; set; }
        public Nullable<long> RetrasoAlmuerzo { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tNM_Colaboradores tNM_Colaboradores { get; set; }
    }
}
