//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNM_JustificacionPermiso
    {
        public int IdJustificacion { get; set; }
        public Nullable<int> IdSolicitudPermiso { get; set; }
        public string NombreArchivo { get; set; }
        public string Extension { get; set; }
        public string UrlJustificacion { get; set; }
    
        public virtual tNM_SolicitudPermiso tNM_SolicitudPermiso { get; set; }
    }
}
