//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNM_FormularioGP
    {
        public int IdFormularioGP { get; set; }
        public int IdEmpresa { get; set; }
        public int IdColaborador { get; set; }
        public int EjercicioFiscal { get; set; }
        public decimal Ingreso { get; set; }
        public decimal OtrosIngresos { get; set; }
        public decimal GastosVivienda { get; set; }
        public decimal GastosEducacion { get; set; }
        public decimal GastosSalud { get; set; }
        public decimal GastosVestimenta { get; set; }
        public decimal GastosAlimentacion { get; set; }
        public decimal AportePersonalIESS { get; set; }
        public decimal BaseImponible { get; set; }
        public decimal ImpuestoARetener { get; set; }
        public decimal PorcentajeRetencion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
        public Nullable<decimal> GastosArte { get; set; }
    
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        public virtual tNM_Colaboradores tNM_Colaboradores { get; set; }
    }
}
