//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPR_DetalleComparativo
    {
        public int IdDetallePresupuesto { get; set; }
        public int IdMaestroPresupuesto { get; set; }
        public Nullable<int> IdPlanCuentasEmpresa { get; set; }
        public Nullable<int> IdCentroCosto { get; set; }
        public Nullable<decimal> Ene { get; set; }
        public Nullable<decimal> Feb { get; set; }
        public Nullable<decimal> Mar { get; set; }
        public Nullable<decimal> Abr { get; set; }
        public Nullable<decimal> May { get; set; }
        public Nullable<decimal> Jun { get; set; }
        public Nullable<decimal> Jul { get; set; }
        public Nullable<decimal> Ago { get; set; }
        public Nullable<decimal> Sep { get; set; }
        public Nullable<decimal> Oct { get; set; }
        public Nullable<decimal> Nov { get; set; }
        public Nullable<decimal> Dic { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> EneA { get; set; }
        public Nullable<decimal> FebA { get; set; }
        public Nullable<decimal> MarA { get; set; }
        public Nullable<decimal> AbrA { get; set; }
        public Nullable<decimal> MayA { get; set; }
        public Nullable<decimal> JunA { get; set; }
        public Nullable<decimal> JulA { get; set; }
        public Nullable<decimal> AgoA { get; set; }
        public Nullable<decimal> SepA { get; set; }
        public Nullable<decimal> OctA { get; set; }
        public Nullable<decimal> NovA { get; set; }
        public Nullable<decimal> DicA { get; set; }
        public Nullable<decimal> TotalA { get; set; }
        public Nullable<decimal> EneR { get; set; }
        public Nullable<decimal> FebR { get; set; }
        public Nullable<decimal> MarR { get; set; }
        public Nullable<decimal> AbrR { get; set; }
        public Nullable<decimal> MayR { get; set; }
        public Nullable<decimal> JunR { get; set; }
        public Nullable<decimal> JulR { get; set; }
        public Nullable<decimal> AgoR { get; set; }
        public Nullable<decimal> SepR { get; set; }
        public Nullable<decimal> OctR { get; set; }
        public Nullable<decimal> NovR { get; set; }
        public Nullable<decimal> DicR { get; set; }
        public Nullable<decimal> TotalR { get; set; }
        public Nullable<decimal> EneAR { get; set; }
        public Nullable<decimal> FebAR { get; set; }
        public Nullable<decimal> MarAR { get; set; }
        public Nullable<decimal> AbrAR { get; set; }
        public Nullable<decimal> MayAR { get; set; }
        public Nullable<decimal> JunAR { get; set; }
        public Nullable<decimal> JulAR { get; set; }
        public Nullable<decimal> AgoAR { get; set; }
        public Nullable<decimal> SepAR { get; set; }
        public Nullable<decimal> OctAR { get; set; }
        public Nullable<decimal> NovAR { get; set; }
        public Nullable<decimal> DicAR { get; set; }
        public Nullable<decimal> TotalAR { get; set; }
        public Nullable<bool> Temporal { get; set; }
        public string CreadoPor { get; set; }
    }
}
