//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPR_MaestroFormulacionFlujoCaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPR_MaestroFormulacionFlujoCaja()
        {
            this.tPR_DetalleFormulacionFlujoCaja = new HashSet<tPR_DetalleFormulacionFlujoCaja>();
        }
    
        public int IdMaestroFormulacion { get; set; }
        public int Ano { get; set; }
        public int IdEmpresa { get; set; }
        public string Descripcion { get; set; }
        public string Origen { get; set; }
        public Nullable<int> OriAno { get; set; }
        public Nullable<int> OriFormId { get; set; }
        public Nullable<bool> Cerrado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string EstacionCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string EstacionModificacion { get; set; }
    
        public virtual tGN_Empresas tGN_Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPR_DetalleFormulacionFlujoCaja> tPR_DetalleFormulacionFlujoCaja { get; set; }
    }
}
