//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRP_Fechas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tRP_Fechas()
        {
            this.tRP_VentasDiariasArea = new HashSet<tRP_VentasDiariasArea>();
            this.tRP_VentasDiariasVendedor = new HashSet<tRP_VentasDiariasVendedor>();
        }
    
        public System.DateTime Fecha { get; set; }
        public string FechaSK { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Trimestre { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Semana { get; set; }
        public Nullable<int> Dia { get; set; }
        public Nullable<int> DiaSemana { get; set; }
        public string Periodo { get; set; }
        public string NTrimestre { get; set; }
        public string NMes { get; set; }
        public string NMes3L { get; set; }
        public string NSemana { get; set; }
        public string NDia { get; set; }
        public string NDia3L { get; set; }
        public string NDiaSemana { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRP_VentasDiariasArea> tRP_VentasDiariasArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRP_VentasDiariasVendedor> tRP_VentasDiariasVendedor { get; set; }
    }
}
