//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GC_SocioPortal
    {
        public int CodigoSocio { get; set; }
        public int Registrado { get; set; }
        public Nullable<int> IdEstadoPublicacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string Identificacion { get; set; }
        public string NombreComercial { get; set; }
        public string RazonSocial { get; set; }
        public string Nombre { get; set; }
        public string RutaLogo { get; set; }
        public string QuienesSomos { get; set; }
        public string Mision { get; set; }
        public string Vision { get; set; }
        public string Direccion { get; set; }
        public string TelefonoPersonal { get; set; }
        public string Email { get; set; }
        public string PaginaWeb { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Youtube { get; set; }
        public string Linkedin { get; set; }
        public string Actividad { get; set; }
    }
}
