//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAsientosContablesCabMayorizados
    {
        public int IdAsientoContableCab { get; set; }
        public string Empresa { get; set; }
        public string Descripcion { get; set; }
        public string GrupoComprobantes { get; set; }
        public Nullable<long> NumeroComprobante { get; set; }
        public Nullable<decimal> TotalDebito { get; set; }
        public Nullable<decimal> TotalCredito { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaComprobante { get; set; }
        public string PeriodoContable { get; set; }
        public int IdEmpresa { get; set; }
    }
}
