//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientesSocios
    {
        public int IdCliente { get; set; }
        public string Identificacion { get; set; }
        public string ApellidoNombre { get; set; }
        public string NombreComercial { get; set; }
        public string RazonSocial { get; set; }
        public string NumeroCuenta { get; set; }
        public string RepresentanteLegal { get; set; }
        public string CorreoElectronico { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public short Ruta { get; set; }
    }
}
