//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCP_ProveedorCargosDescargos
    {
        public int IdEmpresa { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public int IdPeriodoContable { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> IdEstadoDocumento { get; set; }
        public int IdTipoDocumento { get; set; }
        public Nullable<int> IdGrupoComprobante { get; set; }
        public Nullable<long> NumeroComprobante { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    }
}
