//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDatosRepresentantesSociosActivos
    {
        public Nullable<long> Id { get; set; }
        public int Código_de_socio { get; set; }
        public string Estado { get; set; }
        public string Identificación { get; set; }
        public string Razón_social { get; set; }
        public string Representante_legal { get; set; }
        public string Identificación_representante_legal { get; set; }
        public Nullable<System.DateTime> Fecha_nacimiento_representante_legal { get; set; }
        public string Nacionalidad_representante_legal { get; set; }
    }
}
