//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vHistorialPagoClientes
    {
        public Nullable<long> Id { get; set; }
        public Nullable<int> CodigoSocio { get; set; }
        public string Identificacion { get; set; }
        public string RazonSocial { get; set; }
        public string NumeroFactura { get; set; }
        public Nullable<System.DateTime> FechaEmisionFactura { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public string NumeroDescargo { get; set; }
        public Nullable<System.DateTime> FechaEmisionDescargo { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string BancoCheque { get; set; }
        public string CiudadBanco { get; set; }
        public string AgenciaBanco { get; set; }
        public string NumeroCheque { get; set; }
        public string NumeroCuenta { get; set; }
        public Nullable<decimal> ValorCheque { get; set; }
        public Nullable<decimal> ValorTotalEfectivo { get; set; }
        public string BancoTD { get; set; }
        public string Referencia { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Tipo { get; set; }
        public string TarjetaCredito { get; set; }
        public string Recap { get; set; }
        public string NumeroVoucher { get; set; }
        public Nullable<decimal> ValorTarjerta { get; set; }
        public string IdentificacionEmisor { get; set; }
        public string NumeroFacturaRetenciones { get; set; }
        public string NumeroRetencion { get; set; }
        public string TipoRetencion { get; set; }
        public Nullable<decimal> BaseImponible { get; set; }
        public Nullable<decimal> PorcentajeRetencion { get; set; }
        public Nullable<decimal> ValorRetenido { get; set; }
    }
}
