//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vListadoDireccionesSociosActivos
    {
        public Nullable<long> Id { get; set; }
        public int Código_de_Socio { get; set; }
        public string Identificación { get; set; }
        public string Razón_Social { get; set; }
        public string Nombre_Comercial { get; set; }
        public string Nombre_Representante_Legal { get; set; }
        public string Categoría { get; set; }
        public string Tipo_de_Dirección { get; set; }
        public string Dirección { get; set; }
        public string Referencia { get; set; }
        public string Parroquia { get; set; }
        public string Localidad { get; set; }
        public string Teléfono_Convencional_Personal { get; set; }
        public string Teléfono_Celular_Personal { get; set; }
        public string Teléfono_Personal_Facturación { get; set; }
        public string Correos_Electrónicos { get; set; }
    }
}
