//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vVistaSocioNuevo
    {
        public int id { get; set; }
        public string correo { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string nombre_propio { get; set; }
        public string genero { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string nivel_educacion { get; set; }
        public string sector { get; set; }
        public string ciudad { get; set; }
        public string pais { get; set; }
        public string COL1 { get; set; }
        public string COL2 { get; set; }
        public string COL3 { get; set; }
        public string COL4 { get; set; }
        public string COL5 { get; set; }
        public string COL6 { get; set; }
        public string COL7 { get; set; }
        public string COL8 { get; set; }
        public string COL9 { get; set; }
        public string COL10 { get; set; }
        public string COL11 { get; set; }
        public string COL12 { get; set; }
        public string COL13 { get; set; }
        public string COL14 { get; set; }
        public string COL15 { get; set; }
        public string COL16 { get; set; }
        public string COL17 { get; set; }
        public string COL18 { get; set; }
        public string COL19 { get; set; }
        public string COL20 { get; set; }
        public string COL21 { get; set; }
        public string COL22 { get; set; }
        public string COL23 { get; set; }
        public string COL24 { get; set; }
        public string COL25 { get; set; }
        public string COL26 { get; set; }
        public string COL27 { get; set; }
        public string COL28 { get; set; }
        public string COL29 { get; set; }
        public string COL30 { get; set; }
    }
}
