//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTTHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XpoTrackingRecord
    {
        public int OID { get; set; }
        public Nullable<System.Guid> InstanceId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Data { get; set; }
        public string ActivityId { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    }
}
